// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules.Views
{
    partial class AdbFastbootView
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tlpRoot = new System.Windows.Forms.TableLayoutPanel();
            this.flpToolBar = new System.Windows.Forms.FlowLayoutPanel();
            this.lblToolStatus = new System.Windows.Forms.Label();
            this.btnSetTools = new System.Windows.Forms.Button();
            this.btnRefreshDevices = new System.Windows.Forms.Button();
            this.lblDevice = new System.Windows.Forms.Label();
            this.cboDevices = new System.Windows.Forms.ComboBox();
            this.btnAdbDevices = new System.Windows.Forms.Button();
            this.btnFastbootDevices = new System.Windows.Forms.Button();
            this.tabActions = new System.Windows.Forms.TabControl();
            this.tabAdb = new System.Windows.Forms.TabPage();
            this.flpAdb = new System.Windows.Forms.FlowLayoutPanel();
            this.btnAdbReboot = new System.Windows.Forms.Button();
            this.btnAdbRecovery = new System.Windows.Forms.Button();
            this.btnAdbBootloader = new System.Windows.Forms.Button();
            this.btnAdbDownload = new System.Windows.Forms.Button();
            this.btnAdbEdl = new System.Windows.Forms.Button();
            this.btnAdbInstall = new System.Windows.Forms.Button();
            this.btnAdbUninstall = new System.Windows.Forms.Button();
            this.btnAdbPush = new System.Windows.Forms.Button();
            this.btnAdbPull = new System.Windows.Forms.Button();
            this.btnAdbSideload = new System.Windows.Forms.Button();
            this.btnAdbLogcat = new System.Windows.Forms.Button();
            this.btnAdbScreencap = new System.Windows.Forms.Button();
            this.btnAdbShell = new System.Windows.Forms.Button();
            this.btnAdbGetprop = new System.Windows.Forms.Button();
            this.btnAdbPackages = new System.Windows.Forms.Button();
            this.btnAdbBattery = new System.Windows.Forms.Button();
            this.btnAdbScreenSize = new System.Windows.Forms.Button();
            this.btnAdbTcpip = new System.Windows.Forms.Button();
            this.btnAdbConnect = new System.Windows.Forms.Button();
            this.btnAdbBackup = new System.Windows.Forms.Button();
            this.btnAdbRestore = new System.Windows.Forms.Button();
            this.btnAdbKillServer = new System.Windows.Forms.Button();
            this.btnAdbStartServer = new System.Windows.Forms.Button();
            this.tabFastboot = new System.Windows.Forms.TabPage();
            this.flpFastboot = new System.Windows.Forms.FlowLayoutPanel();
            this.btnFbGetvar = new System.Windows.Forms.Button();
            this.btnFbUnlock = new System.Windows.Forms.Button();
            this.btnFbOemUnlock = new System.Windows.Forms.Button();
            this.btnFbLock = new System.Windows.Forms.Button();
            this.btnFbReboot = new System.Windows.Forms.Button();
            this.btnFbBootloader = new System.Windows.Forms.Button();
            this.btnFbRecovery = new System.Windows.Forms.Button();
            this.btnFbFastbootd = new System.Windows.Forms.Button();
            this.btnFbBootImg = new System.Windows.Forms.Button();
            this.btnFbFlashPartition = new System.Windows.Forms.Button();
            this.btnFbFlashBoot = new System.Windows.Forms.Button();
            this.btnFbFlashRecovery = new System.Windows.Forms.Button();
            this.btnFbErase = new System.Windows.Forms.Button();
            this.btnFbFormat = new System.Windows.Forms.Button();
            this.btnFbActiveA = new System.Windows.Forms.Button();
            this.btnFbActiveB = new System.Windows.Forms.Button();
            this.btnFbWipe = new System.Windows.Forms.Button();
            this.btnFbContinue = new System.Windows.Forms.Button();
            this.tabDownload = new System.Windows.Forms.TabPage();
            this.flpDownload = new System.Windows.Forms.FlowLayoutPanel();
            this.btnDlSamsung = new System.Windows.Forms.Button();
            this.btnDlEdlAdb = new System.Windows.Forms.Button();
            this.btnDlEdlFastboot = new System.Windows.Forms.Button();
            this.btnHeimdallDetect = new System.Windows.Forms.Button();
            this.btnHeimdallPit = new System.Windows.Forms.Button();
            this.btnHeimdallFlash = new System.Windows.Forms.Button();
            this.btnRecReboot = new System.Windows.Forms.Button();
            this.btnRecSideload = new System.Windows.Forms.Button();
            this.lblVendorNote = new System.Windows.Forms.Label();
            this.txtConsole = new System.Windows.Forms.TextBox();
            this.tlpCommandBar = new System.Windows.Forms.TableLayoutPanel();
            this.txtCommand = new System.Windows.Forms.TextBox();
            this.btnRun = new System.Windows.Forms.Button();
            this.btnStop = new System.Windows.Forms.Button();
            this.btnClear = new System.Windows.Forms.Button();
            this.tlpRoot.SuspendLayout();
            this.flpToolBar.SuspendLayout();
            this.tabActions.SuspendLayout();
            this.tabAdb.SuspendLayout();
            this.flpAdb.SuspendLayout();
            this.tabFastboot.SuspendLayout();
            this.flpFastboot.SuspendLayout();
            this.tabDownload.SuspendLayout();
            this.flpDownload.SuspendLayout();
            this.tlpCommandBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpRoot
            // 
            this.tlpRoot.Controls.Add(this.flpToolBar, 0, 0);
            this.tlpRoot.Controls.Add(this.tabActions, 0, 1);
            this.tlpRoot.Controls.Add(this.txtConsole, 0, 2);
            this.tlpRoot.Controls.Add(this.tlpCommandBar, 0, 3);
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 42F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 58F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRoot.ColumnCount = 1;
            this.tlpRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRoot.RowCount = 4;
            this.tlpRoot.Padding = new System.Windows.Forms.Padding(8);
            this.tlpRoot.Name = "tlpRoot";
            // 
            // flpToolBar
            // 
            this.flpToolBar.Controls.Add(this.lblToolStatus);
            this.flpToolBar.Controls.Add(this.btnSetTools);
            this.flpToolBar.Controls.Add(this.btnRefreshDevices);
            this.flpToolBar.Controls.Add(this.lblDevice);
            this.flpToolBar.Controls.Add(this.cboDevices);
            this.flpToolBar.Controls.Add(this.btnAdbDevices);
            this.flpToolBar.Controls.Add(this.btnFastbootDevices);
            this.flpToolBar.AutoSize = true;
            this.flpToolBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpToolBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpToolBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpToolBar.Name = "flpToolBar";
            // 
            // lblToolStatus
            // 
            this.lblToolStatus.AutoSize = true;
            this.lblToolStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblToolStatus.Text = "Tools:";
            this.lblToolStatus.Margin = new System.Windows.Forms.Padding(0, 6, 12, 0);
            this.lblToolStatus.Name = "lblToolStatus";
            // 
            // btnSetTools
            // 
            this.btnSetTools.AutoSize = true;
            this.btnSetTools.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnSetTools.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSetTools.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnSetTools.Margin = new System.Windows.Forms.Padding(3);
            this.btnSetTools.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnSetTools.Text = "Set platform-tools…";
            this.btnSetTools.UseVisualStyleBackColor = false;
            this.btnSetTools.Name = "btnSetTools";
            this.btnSetTools.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnSetTools.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnRefreshDevices
            // 
            this.btnRefreshDevices.AutoSize = true;
            this.btnRefreshDevices.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRefreshDevices.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRefreshDevices.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRefreshDevices.Margin = new System.Windows.Forms.Padding(3);
            this.btnRefreshDevices.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnRefreshDevices.Text = "Refresh devices";
            this.btnRefreshDevices.UseVisualStyleBackColor = false;
            this.btnRefreshDevices.Name = "btnRefreshDevices";
            this.btnRefreshDevices.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRefreshDevices.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // lblDevice
            // 
            this.lblDevice.AutoSize = true;
            this.lblDevice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblDevice.Text = "Device:";
            this.lblDevice.Margin = new System.Windows.Forms.Padding(8, 6, 4, 0);
            this.lblDevice.Name = "lblDevice";
            // 
            // cboDevices
            // 
            this.cboDevices.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboDevices.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDevices.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboDevices.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboDevices.FormattingEnabled = true;
            this.cboDevices.Size = new System.Drawing.Size(260, 25);
            this.cboDevices.Name = "cboDevices";
            // 
            // btnAdbDevices
            // 
            this.btnAdbDevices.AutoSize = true;
            this.btnAdbDevices.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbDevices.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbDevices.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbDevices.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbDevices.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbDevices.Text = "adb devices";
            this.btnAdbDevices.UseVisualStyleBackColor = false;
            this.btnAdbDevices.Name = "btnAdbDevices";
            this.btnAdbDevices.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbDevices.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFastbootDevices
            // 
            this.btnFastbootDevices.AutoSize = true;
            this.btnFastbootDevices.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFastbootDevices.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFastbootDevices.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFastbootDevices.Margin = new System.Windows.Forms.Padding(3);
            this.btnFastbootDevices.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFastbootDevices.Text = "fastboot devices";
            this.btnFastbootDevices.UseVisualStyleBackColor = false;
            this.btnFastbootDevices.Name = "btnFastbootDevices";
            this.btnFastbootDevices.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFastbootDevices.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // tabActions
            // 
            this.tabActions.Controls.Add(this.tabAdb);
            this.tabActions.Controls.Add(this.tabFastboot);
            this.tabActions.Controls.Add(this.tabDownload);
            this.tabActions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabActions.SelectedIndex = 0;
            this.tabActions.Name = "tabActions";
            // 
            // tabAdb
            // 
            this.tabAdb.Controls.Add(this.flpAdb);
            this.tabAdb.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tabAdb.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tabAdb.Padding = new System.Windows.Forms.Padding(3);
            this.tabAdb.Text = "ADB";
            this.tabAdb.UseVisualStyleBackColor = false;
            this.tabAdb.Name = "tabAdb";
            // 
            // flpAdb
            // 
            this.flpAdb.Controls.Add(this.btnAdbReboot);
            this.flpAdb.Controls.Add(this.btnAdbRecovery);
            this.flpAdb.Controls.Add(this.btnAdbBootloader);
            this.flpAdb.Controls.Add(this.btnAdbDownload);
            this.flpAdb.Controls.Add(this.btnAdbEdl);
            this.flpAdb.Controls.Add(this.btnAdbInstall);
            this.flpAdb.Controls.Add(this.btnAdbUninstall);
            this.flpAdb.Controls.Add(this.btnAdbPush);
            this.flpAdb.Controls.Add(this.btnAdbPull);
            this.flpAdb.Controls.Add(this.btnAdbSideload);
            this.flpAdb.Controls.Add(this.btnAdbLogcat);
            this.flpAdb.Controls.Add(this.btnAdbScreencap);
            this.flpAdb.Controls.Add(this.btnAdbShell);
            this.flpAdb.Controls.Add(this.btnAdbGetprop);
            this.flpAdb.Controls.Add(this.btnAdbPackages);
            this.flpAdb.Controls.Add(this.btnAdbBattery);
            this.flpAdb.Controls.Add(this.btnAdbScreenSize);
            this.flpAdb.Controls.Add(this.btnAdbTcpip);
            this.flpAdb.Controls.Add(this.btnAdbConnect);
            this.flpAdb.Controls.Add(this.btnAdbBackup);
            this.flpAdb.Controls.Add(this.btnAdbRestore);
            this.flpAdb.Controls.Add(this.btnAdbKillServer);
            this.flpAdb.Controls.Add(this.btnAdbStartServer);
            this.flpAdb.AutoSize = false;
            this.flpAdb.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpAdb.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpAdb.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpAdb.AutoScroll = true;
            this.flpAdb.Padding = new System.Windows.Forms.Padding(4);
            this.flpAdb.Name = "flpAdb";
            // 
            // btnAdbReboot
            // 
            this.btnAdbReboot.AutoSize = true;
            this.btnAdbReboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbReboot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbReboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbReboot.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbReboot.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbReboot.Text = "Reboot";
            this.btnAdbReboot.UseVisualStyleBackColor = false;
            this.btnAdbReboot.Name = "btnAdbReboot";
            this.btnAdbReboot.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbReboot.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbRecovery
            // 
            this.btnAdbRecovery.AutoSize = true;
            this.btnAdbRecovery.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbRecovery.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbRecovery.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbRecovery.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbRecovery.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbRecovery.Text = "→ Recovery";
            this.btnAdbRecovery.UseVisualStyleBackColor = false;
            this.btnAdbRecovery.Name = "btnAdbRecovery";
            this.btnAdbRecovery.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbRecovery.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbBootloader
            // 
            this.btnAdbBootloader.AutoSize = true;
            this.btnAdbBootloader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbBootloader.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbBootloader.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbBootloader.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbBootloader.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbBootloader.Text = "→ Bootloader";
            this.btnAdbBootloader.UseVisualStyleBackColor = false;
            this.btnAdbBootloader.Name = "btnAdbBootloader";
            this.btnAdbBootloader.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbBootloader.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbDownload
            // 
            this.btnAdbDownload.AutoSize = true;
            this.btnAdbDownload.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbDownload.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbDownload.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbDownload.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbDownload.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbDownload.Text = "→ Download";
            this.btnAdbDownload.UseVisualStyleBackColor = false;
            this.btnAdbDownload.Name = "btnAdbDownload";
            this.btnAdbDownload.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbDownload.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbEdl
            // 
            this.btnAdbEdl.AutoSize = true;
            this.btnAdbEdl.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbEdl.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbEdl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbEdl.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbEdl.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbEdl.Text = "→ EDL (9008)";
            this.btnAdbEdl.UseVisualStyleBackColor = false;
            this.btnAdbEdl.Name = "btnAdbEdl";
            this.btnAdbEdl.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbEdl.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbInstall
            // 
            this.btnAdbInstall.AutoSize = true;
            this.btnAdbInstall.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbInstall.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbInstall.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbInstall.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbInstall.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbInstall.Text = "Install APK…";
            this.btnAdbInstall.UseVisualStyleBackColor = false;
            this.btnAdbInstall.Name = "btnAdbInstall";
            this.btnAdbInstall.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbInstall.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbUninstall
            // 
            this.btnAdbUninstall.AutoSize = true;
            this.btnAdbUninstall.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbUninstall.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbUninstall.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbUninstall.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbUninstall.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbUninstall.Text = "Uninstall pkg…";
            this.btnAdbUninstall.UseVisualStyleBackColor = false;
            this.btnAdbUninstall.Name = "btnAdbUninstall";
            this.btnAdbUninstall.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbUninstall.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbPush
            // 
            this.btnAdbPush.AutoSize = true;
            this.btnAdbPush.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbPush.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbPush.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbPush.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbPush.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbPush.Text = "Push file…";
            this.btnAdbPush.UseVisualStyleBackColor = false;
            this.btnAdbPush.Name = "btnAdbPush";
            this.btnAdbPush.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbPush.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbPull
            // 
            this.btnAdbPull.AutoSize = true;
            this.btnAdbPull.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbPull.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbPull.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbPull.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbPull.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbPull.Text = "Pull file…";
            this.btnAdbPull.UseVisualStyleBackColor = false;
            this.btnAdbPull.Name = "btnAdbPull";
            this.btnAdbPull.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbPull.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbSideload
            // 
            this.btnAdbSideload.AutoSize = true;
            this.btnAdbSideload.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbSideload.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbSideload.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbSideload.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbSideload.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbSideload.Text = "Sideload OTA…";
            this.btnAdbSideload.UseVisualStyleBackColor = false;
            this.btnAdbSideload.Name = "btnAdbSideload";
            this.btnAdbSideload.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbSideload.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbLogcat
            // 
            this.btnAdbLogcat.AutoSize = true;
            this.btnAdbLogcat.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbLogcat.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbLogcat.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbLogcat.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbLogcat.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbLogcat.Text = "Logcat";
            this.btnAdbLogcat.UseVisualStyleBackColor = false;
            this.btnAdbLogcat.Name = "btnAdbLogcat";
            this.btnAdbLogcat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbLogcat.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbScreencap
            // 
            this.btnAdbScreencap.AutoSize = true;
            this.btnAdbScreencap.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbScreencap.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbScreencap.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbScreencap.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbScreencap.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbScreencap.Text = "Screencap…";
            this.btnAdbScreencap.UseVisualStyleBackColor = false;
            this.btnAdbScreencap.Name = "btnAdbScreencap";
            this.btnAdbScreencap.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbScreencap.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbShell
            // 
            this.btnAdbShell.AutoSize = true;
            this.btnAdbShell.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbShell.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbShell.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbShell.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbShell.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbShell.Text = "Interactive shell";
            this.btnAdbShell.UseVisualStyleBackColor = false;
            this.btnAdbShell.Name = "btnAdbShell";
            this.btnAdbShell.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbShell.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbGetprop
            // 
            this.btnAdbGetprop.AutoSize = true;
            this.btnAdbGetprop.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbGetprop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbGetprop.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbGetprop.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbGetprop.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbGetprop.Text = "getprop";
            this.btnAdbGetprop.UseVisualStyleBackColor = false;
            this.btnAdbGetprop.Name = "btnAdbGetprop";
            this.btnAdbGetprop.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbGetprop.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbPackages
            // 
            this.btnAdbPackages.AutoSize = true;
            this.btnAdbPackages.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbPackages.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbPackages.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbPackages.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbPackages.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbPackages.Text = "List packages";
            this.btnAdbPackages.UseVisualStyleBackColor = false;
            this.btnAdbPackages.Name = "btnAdbPackages";
            this.btnAdbPackages.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbPackages.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbBattery
            // 
            this.btnAdbBattery.AutoSize = true;
            this.btnAdbBattery.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbBattery.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbBattery.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbBattery.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbBattery.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbBattery.Text = "Battery";
            this.btnAdbBattery.UseVisualStyleBackColor = false;
            this.btnAdbBattery.Name = "btnAdbBattery";
            this.btnAdbBattery.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbBattery.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbScreenSize
            // 
            this.btnAdbScreenSize.AutoSize = true;
            this.btnAdbScreenSize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbScreenSize.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbScreenSize.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbScreenSize.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbScreenSize.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbScreenSize.Text = "Screen size";
            this.btnAdbScreenSize.UseVisualStyleBackColor = false;
            this.btnAdbScreenSize.Name = "btnAdbScreenSize";
            this.btnAdbScreenSize.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbScreenSize.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbTcpip
            // 
            this.btnAdbTcpip.AutoSize = true;
            this.btnAdbTcpip.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbTcpip.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbTcpip.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbTcpip.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbTcpip.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbTcpip.Text = "Wi-Fi: tcpip 5555";
            this.btnAdbTcpip.UseVisualStyleBackColor = false;
            this.btnAdbTcpip.Name = "btnAdbTcpip";
            this.btnAdbTcpip.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbTcpip.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbConnect
            // 
            this.btnAdbConnect.AutoSize = true;
            this.btnAdbConnect.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbConnect.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbConnect.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbConnect.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbConnect.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbConnect.Text = "Wi-Fi: connect…";
            this.btnAdbConnect.UseVisualStyleBackColor = false;
            this.btnAdbConnect.Name = "btnAdbConnect";
            this.btnAdbConnect.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbConnect.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbBackup
            // 
            this.btnAdbBackup.AutoSize = true;
            this.btnAdbBackup.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbBackup.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbBackup.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbBackup.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbBackup.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbBackup.Text = "Backup…";
            this.btnAdbBackup.UseVisualStyleBackColor = false;
            this.btnAdbBackup.Name = "btnAdbBackup";
            this.btnAdbBackup.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbBackup.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbRestore
            // 
            this.btnAdbRestore.AutoSize = true;
            this.btnAdbRestore.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbRestore.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbRestore.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbRestore.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbRestore.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbRestore.Text = "Restore…";
            this.btnAdbRestore.UseVisualStyleBackColor = false;
            this.btnAdbRestore.Name = "btnAdbRestore";
            this.btnAdbRestore.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbRestore.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbKillServer
            // 
            this.btnAdbKillServer.AutoSize = true;
            this.btnAdbKillServer.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbKillServer.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbKillServer.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbKillServer.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbKillServer.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbKillServer.Text = "Kill server";
            this.btnAdbKillServer.UseVisualStyleBackColor = false;
            this.btnAdbKillServer.Name = "btnAdbKillServer";
            this.btnAdbKillServer.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbKillServer.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnAdbStartServer
            // 
            this.btnAdbStartServer.AutoSize = true;
            this.btnAdbStartServer.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdbStartServer.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdbStartServer.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdbStartServer.Margin = new System.Windows.Forms.Padding(3);
            this.btnAdbStartServer.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnAdbStartServer.Text = "Start server";
            this.btnAdbStartServer.UseVisualStyleBackColor = false;
            this.btnAdbStartServer.Name = "btnAdbStartServer";
            this.btnAdbStartServer.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdbStartServer.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // tabFastboot
            // 
            this.tabFastboot.Controls.Add(this.flpFastboot);
            this.tabFastboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tabFastboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tabFastboot.Padding = new System.Windows.Forms.Padding(3);
            this.tabFastboot.Text = "Fastboot";
            this.tabFastboot.UseVisualStyleBackColor = false;
            this.tabFastboot.Name = "tabFastboot";
            // 
            // flpFastboot
            // 
            this.flpFastboot.Controls.Add(this.btnFbGetvar);
            this.flpFastboot.Controls.Add(this.btnFbUnlock);
            this.flpFastboot.Controls.Add(this.btnFbOemUnlock);
            this.flpFastboot.Controls.Add(this.btnFbLock);
            this.flpFastboot.Controls.Add(this.btnFbReboot);
            this.flpFastboot.Controls.Add(this.btnFbBootloader);
            this.flpFastboot.Controls.Add(this.btnFbRecovery);
            this.flpFastboot.Controls.Add(this.btnFbFastbootd);
            this.flpFastboot.Controls.Add(this.btnFbBootImg);
            this.flpFastboot.Controls.Add(this.btnFbFlashPartition);
            this.flpFastboot.Controls.Add(this.btnFbFlashBoot);
            this.flpFastboot.Controls.Add(this.btnFbFlashRecovery);
            this.flpFastboot.Controls.Add(this.btnFbErase);
            this.flpFastboot.Controls.Add(this.btnFbFormat);
            this.flpFastboot.Controls.Add(this.btnFbActiveA);
            this.flpFastboot.Controls.Add(this.btnFbActiveB);
            this.flpFastboot.Controls.Add(this.btnFbWipe);
            this.flpFastboot.Controls.Add(this.btnFbContinue);
            this.flpFastboot.AutoSize = false;
            this.flpFastboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpFastboot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpFastboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpFastboot.AutoScroll = true;
            this.flpFastboot.Padding = new System.Windows.Forms.Padding(4);
            this.flpFastboot.Name = "flpFastboot";
            // 
            // btnFbGetvar
            // 
            this.btnFbGetvar.AutoSize = true;
            this.btnFbGetvar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbGetvar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbGetvar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbGetvar.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbGetvar.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbGetvar.Text = "getvar all";
            this.btnFbGetvar.UseVisualStyleBackColor = false;
            this.btnFbGetvar.Name = "btnFbGetvar";
            this.btnFbGetvar.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbGetvar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbUnlock
            // 
            this.btnFbUnlock.AutoSize = true;
            this.btnFbUnlock.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbUnlock.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbUnlock.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbUnlock.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbUnlock.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbUnlock.Text = "Unlock";
            this.btnFbUnlock.UseVisualStyleBackColor = false;
            this.btnFbUnlock.Name = "btnFbUnlock";
            this.btnFbUnlock.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbUnlock.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbOemUnlock
            // 
            this.btnFbOemUnlock.AutoSize = true;
            this.btnFbOemUnlock.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbOemUnlock.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbOemUnlock.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbOemUnlock.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbOemUnlock.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbOemUnlock.Text = "OEM unlock";
            this.btnFbOemUnlock.UseVisualStyleBackColor = false;
            this.btnFbOemUnlock.Name = "btnFbOemUnlock";
            this.btnFbOemUnlock.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbOemUnlock.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbLock
            // 
            this.btnFbLock.AutoSize = true;
            this.btnFbLock.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbLock.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbLock.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbLock.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbLock.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbLock.Text = "Lock";
            this.btnFbLock.UseVisualStyleBackColor = false;
            this.btnFbLock.Name = "btnFbLock";
            this.btnFbLock.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbLock.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbReboot
            // 
            this.btnFbReboot.AutoSize = true;
            this.btnFbReboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbReboot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbReboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbReboot.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbReboot.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbReboot.Text = "Reboot";
            this.btnFbReboot.UseVisualStyleBackColor = false;
            this.btnFbReboot.Name = "btnFbReboot";
            this.btnFbReboot.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbReboot.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbBootloader
            // 
            this.btnFbBootloader.AutoSize = true;
            this.btnFbBootloader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbBootloader.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbBootloader.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbBootloader.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbBootloader.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbBootloader.Text = "→ Bootloader";
            this.btnFbBootloader.UseVisualStyleBackColor = false;
            this.btnFbBootloader.Name = "btnFbBootloader";
            this.btnFbBootloader.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbBootloader.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbRecovery
            // 
            this.btnFbRecovery.AutoSize = true;
            this.btnFbRecovery.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbRecovery.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbRecovery.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbRecovery.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbRecovery.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbRecovery.Text = "→ Recovery";
            this.btnFbRecovery.UseVisualStyleBackColor = false;
            this.btnFbRecovery.Name = "btnFbRecovery";
            this.btnFbRecovery.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbRecovery.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbFastbootd
            // 
            this.btnFbFastbootd.AutoSize = true;
            this.btnFbFastbootd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbFastbootd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbFastbootd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbFastbootd.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbFastbootd.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbFastbootd.Text = "→ fastbootd";
            this.btnFbFastbootd.UseVisualStyleBackColor = false;
            this.btnFbFastbootd.Name = "btnFbFastbootd";
            this.btnFbFastbootd.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbFastbootd.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbBootImg
            // 
            this.btnFbBootImg.AutoSize = true;
            this.btnFbBootImg.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbBootImg.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbBootImg.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbBootImg.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbBootImg.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbBootImg.Text = "Boot img (temp)…";
            this.btnFbBootImg.UseVisualStyleBackColor = false;
            this.btnFbBootImg.Name = "btnFbBootImg";
            this.btnFbBootImg.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbBootImg.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbFlashPartition
            // 
            this.btnFbFlashPartition.AutoSize = true;
            this.btnFbFlashPartition.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbFlashPartition.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbFlashPartition.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbFlashPartition.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbFlashPartition.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbFlashPartition.Text = "Flash partition…";
            this.btnFbFlashPartition.UseVisualStyleBackColor = false;
            this.btnFbFlashPartition.Name = "btnFbFlashPartition";
            this.btnFbFlashPartition.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbFlashPartition.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbFlashBoot
            // 
            this.btnFbFlashBoot.AutoSize = true;
            this.btnFbFlashBoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbFlashBoot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbFlashBoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbFlashBoot.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbFlashBoot.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbFlashBoot.Text = "Flash boot…";
            this.btnFbFlashBoot.UseVisualStyleBackColor = false;
            this.btnFbFlashBoot.Name = "btnFbFlashBoot";
            this.btnFbFlashBoot.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbFlashBoot.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbFlashRecovery
            // 
            this.btnFbFlashRecovery.AutoSize = true;
            this.btnFbFlashRecovery.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbFlashRecovery.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbFlashRecovery.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbFlashRecovery.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbFlashRecovery.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbFlashRecovery.Text = "Flash recovery…";
            this.btnFbFlashRecovery.UseVisualStyleBackColor = false;
            this.btnFbFlashRecovery.Name = "btnFbFlashRecovery";
            this.btnFbFlashRecovery.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbFlashRecovery.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbErase
            // 
            this.btnFbErase.AutoSize = true;
            this.btnFbErase.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbErase.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbErase.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbErase.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbErase.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbErase.Text = "Erase partition…";
            this.btnFbErase.UseVisualStyleBackColor = false;
            this.btnFbErase.Name = "btnFbErase";
            this.btnFbErase.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbErase.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbFormat
            // 
            this.btnFbFormat.AutoSize = true;
            this.btnFbFormat.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbFormat.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbFormat.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbFormat.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbFormat.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbFormat.Text = "Format partition…";
            this.btnFbFormat.UseVisualStyleBackColor = false;
            this.btnFbFormat.Name = "btnFbFormat";
            this.btnFbFormat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbFormat.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbActiveA
            // 
            this.btnFbActiveA.AutoSize = true;
            this.btnFbActiveA.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbActiveA.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbActiveA.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbActiveA.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbActiveA.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbActiveA.Text = "Set active a";
            this.btnFbActiveA.UseVisualStyleBackColor = false;
            this.btnFbActiveA.Name = "btnFbActiveA";
            this.btnFbActiveA.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbActiveA.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbActiveB
            // 
            this.btnFbActiveB.AutoSize = true;
            this.btnFbActiveB.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbActiveB.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbActiveB.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbActiveB.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbActiveB.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbActiveB.Text = "Set active b";
            this.btnFbActiveB.UseVisualStyleBackColor = false;
            this.btnFbActiveB.Name = "btnFbActiveB";
            this.btnFbActiveB.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbActiveB.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbWipe
            // 
            this.btnFbWipe.AutoSize = true;
            this.btnFbWipe.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbWipe.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbWipe.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbWipe.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbWipe.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbWipe.Text = "Wipe (-w)";
            this.btnFbWipe.UseVisualStyleBackColor = false;
            this.btnFbWipe.Name = "btnFbWipe";
            this.btnFbWipe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbWipe.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnFbContinue
            // 
            this.btnFbContinue.AutoSize = true;
            this.btnFbContinue.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnFbContinue.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFbContinue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnFbContinue.Margin = new System.Windows.Forms.Padding(3);
            this.btnFbContinue.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnFbContinue.Text = "Continue";
            this.btnFbContinue.UseVisualStyleBackColor = false;
            this.btnFbContinue.Name = "btnFbContinue";
            this.btnFbContinue.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnFbContinue.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // tabDownload
            // 
            this.tabDownload.Controls.Add(this.flpDownload);
            this.tabDownload.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tabDownload.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tabDownload.Padding = new System.Windows.Forms.Padding(3);
            this.tabDownload.Text = "Download / Recovery";
            this.tabDownload.UseVisualStyleBackColor = false;
            this.tabDownload.Name = "tabDownload";
            // 
            // flpDownload
            // 
            this.flpDownload.Controls.Add(this.btnDlSamsung);
            this.flpDownload.Controls.Add(this.btnDlEdlAdb);
            this.flpDownload.Controls.Add(this.btnDlEdlFastboot);
            this.flpDownload.Controls.Add(this.btnHeimdallDetect);
            this.flpDownload.Controls.Add(this.btnHeimdallPit);
            this.flpDownload.Controls.Add(this.btnHeimdallFlash);
            this.flpDownload.Controls.Add(this.btnRecReboot);
            this.flpDownload.Controls.Add(this.btnRecSideload);
            this.flpDownload.Controls.Add(this.lblVendorNote);
            this.flpDownload.AutoSize = false;
            this.flpDownload.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpDownload.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpDownload.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpDownload.AutoScroll = true;
            this.flpDownload.Padding = new System.Windows.Forms.Padding(4);
            this.flpDownload.Name = "flpDownload";
            // 
            // btnDlSamsung
            // 
            this.btnDlSamsung.AutoSize = true;
            this.btnDlSamsung.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnDlSamsung.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDlSamsung.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnDlSamsung.Margin = new System.Windows.Forms.Padding(3);
            this.btnDlSamsung.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnDlSamsung.Text = "Enter Download (Samsung)";
            this.btnDlSamsung.UseVisualStyleBackColor = false;
            this.btnDlSamsung.Name = "btnDlSamsung";
            this.btnDlSamsung.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnDlSamsung.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnDlEdlAdb
            // 
            this.btnDlEdlAdb.AutoSize = true;
            this.btnDlEdlAdb.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnDlEdlAdb.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDlEdlAdb.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnDlEdlAdb.Margin = new System.Windows.Forms.Padding(3);
            this.btnDlEdlAdb.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnDlEdlAdb.Text = "Enter EDL (adb)";
            this.btnDlEdlAdb.UseVisualStyleBackColor = false;
            this.btnDlEdlAdb.Name = "btnDlEdlAdb";
            this.btnDlEdlAdb.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnDlEdlAdb.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnDlEdlFastboot
            // 
            this.btnDlEdlFastboot.AutoSize = true;
            this.btnDlEdlFastboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnDlEdlFastboot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDlEdlFastboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnDlEdlFastboot.Margin = new System.Windows.Forms.Padding(3);
            this.btnDlEdlFastboot.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnDlEdlFastboot.Text = "Enter EDL (fastboot)";
            this.btnDlEdlFastboot.UseVisualStyleBackColor = false;
            this.btnDlEdlFastboot.Name = "btnDlEdlFastboot";
            this.btnDlEdlFastboot.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnDlEdlFastboot.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnHeimdallDetect
            // 
            this.btnHeimdallDetect.AutoSize = true;
            this.btnHeimdallDetect.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnHeimdallDetect.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnHeimdallDetect.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnHeimdallDetect.Margin = new System.Windows.Forms.Padding(3);
            this.btnHeimdallDetect.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnHeimdallDetect.Text = "Heimdall: detect";
            this.btnHeimdallDetect.UseVisualStyleBackColor = false;
            this.btnHeimdallDetect.Name = "btnHeimdallDetect";
            this.btnHeimdallDetect.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnHeimdallDetect.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnHeimdallPit
            // 
            this.btnHeimdallPit.AutoSize = true;
            this.btnHeimdallPit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnHeimdallPit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnHeimdallPit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnHeimdallPit.Margin = new System.Windows.Forms.Padding(3);
            this.btnHeimdallPit.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnHeimdallPit.Text = "Heimdall: print-pit";
            this.btnHeimdallPit.UseVisualStyleBackColor = false;
            this.btnHeimdallPit.Name = "btnHeimdallPit";
            this.btnHeimdallPit.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnHeimdallPit.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnHeimdallFlash
            // 
            this.btnHeimdallFlash.AutoSize = true;
            this.btnHeimdallFlash.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnHeimdallFlash.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnHeimdallFlash.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnHeimdallFlash.Margin = new System.Windows.Forms.Padding(3);
            this.btnHeimdallFlash.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnHeimdallFlash.Text = "Heimdall: flash partition…";
            this.btnHeimdallFlash.UseVisualStyleBackColor = false;
            this.btnHeimdallFlash.Name = "btnHeimdallFlash";
            this.btnHeimdallFlash.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnHeimdallFlash.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnRecReboot
            // 
            this.btnRecReboot.AutoSize = true;
            this.btnRecReboot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRecReboot.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRecReboot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRecReboot.Margin = new System.Windows.Forms.Padding(3);
            this.btnRecReboot.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnRecReboot.Text = "Recovery: reboot";
            this.btnRecReboot.UseVisualStyleBackColor = false;
            this.btnRecReboot.Name = "btnRecReboot";
            this.btnRecReboot.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRecReboot.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnRecSideload
            // 
            this.btnRecSideload.AutoSize = true;
            this.btnRecSideload.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRecSideload.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRecSideload.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRecSideload.Margin = new System.Windows.Forms.Padding(3);
            this.btnRecSideload.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnRecSideload.Text = "Recovery: sideload OTA…";
            this.btnRecSideload.UseVisualStyleBackColor = false;
            this.btnRecSideload.Name = "btnRecSideload";
            this.btnRecSideload.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRecSideload.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // lblVendorNote
            // 
            this.lblVendorNote.AutoSize = true;
            this.lblVendorNote.ForeColor = System.Drawing.Color.DimGray;
            this.lblVendorNote.Text = "Samsung Odin and Qualcomm QFIL/EDL flashing are vendor GUIs.\r\nUse these to ENTER the mode; use Heimdall (open Odin) or QFIL to flash.";
            this.lblVendorNote.Margin = new System.Windows.Forms.Padding(4, 10, 4, 4);
            this.lblVendorNote.Name = "lblVendorNote";
            // 
            // txtConsole
            // 
            this.txtConsole.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.txtConsole.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtConsole.ForeColor = System.Drawing.Color.Gainsboro;
            this.txtConsole.ReadOnly = true;
            this.txtConsole.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtConsole.Font = new System.Drawing.Font("Consolas", 9.5F);
            this.txtConsole.Multiline = true;
            this.txtConsole.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.txtConsole.WordWrap = false;
            this.txtConsole.Name = "txtConsole";
            // 
            // tlpCommandBar
            // 
            this.tlpCommandBar.Controls.Add(this.txtCommand, 0, 0);
            this.tlpCommandBar.Controls.Add(this.btnRun, 1, 0);
            this.tlpCommandBar.Controls.Add(this.btnStop, 2, 0);
            this.tlpCommandBar.Controls.Add(this.btnClear, 3, 0);
            this.tlpCommandBar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpCommandBar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpCommandBar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpCommandBar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpCommandBar.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpCommandBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpCommandBar.ColumnCount = 4;
            this.tlpCommandBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpCommandBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpCommandBar.RowCount = 1;
            this.tlpCommandBar.AutoSize = true;
            this.tlpCommandBar.Name = "tlpCommandBar";
            // 
            // txtCommand
            // 
            this.txtCommand.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.txtCommand.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCommand.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtCommand.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCommand.Font = new System.Drawing.Font("Consolas", 9.5F);
            this.txtCommand.Name = "txtCommand";
            // 
            // btnRun
            // 
            this.btnRun.AutoSize = true;
            this.btnRun.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRun.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRun.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRun.Margin = new System.Windows.Forms.Padding(3);
            this.btnRun.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnRun.Text = "Run / Send";
            this.btnRun.UseVisualStyleBackColor = false;
            this.btnRun.Name = "btnRun";
            this.btnRun.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRun.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnStop
            // 
            this.btnStop.AutoSize = true;
            this.btnStop.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnStop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStop.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnStop.Margin = new System.Windows.Forms.Padding(3);
            this.btnStop.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnStop.Text = "Stop";
            this.btnStop.UseVisualStyleBackColor = false;
            this.btnStop.Name = "btnStop";
            this.btnStop.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnStop.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnClear
            // 
            this.btnClear.AutoSize = true;
            this.btnClear.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClear.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnClear.Margin = new System.Windows.Forms.Padding(3);
            this.btnClear.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnClear.Text = "Clear";
            this.btnClear.UseVisualStyleBackColor = false;
            this.btnClear.Name = "btnClear";
            this.btnClear.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnClear.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // AdbFastbootView
            // 
            this.Controls.Add(this.tlpRoot);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.Size = new System.Drawing.Size(1000, 680);
            this.Name = "AdbFastbootView";
            this.tlpCommandBar.ResumeLayout(false);
            this.tlpCommandBar.PerformLayout();
            this.flpDownload.ResumeLayout(false);
            this.flpDownload.PerformLayout();
            this.tabDownload.ResumeLayout(false);
            this.tabDownload.PerformLayout();
            this.flpFastboot.ResumeLayout(false);
            this.flpFastboot.PerformLayout();
            this.tabFastboot.ResumeLayout(false);
            this.tabFastboot.PerformLayout();
            this.flpAdb.ResumeLayout(false);
            this.flpAdb.PerformLayout();
            this.tabAdb.ResumeLayout(false);
            this.tabAdb.PerformLayout();
            this.tabActions.ResumeLayout(false);
            this.tabActions.PerformLayout();
            this.flpToolBar.ResumeLayout(false);
            this.flpToolBar.PerformLayout();
            this.tlpRoot.ResumeLayout(false);
            this.tlpRoot.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.TableLayoutPanel tlpRoot;
        internal System.Windows.Forms.FlowLayoutPanel flpToolBar;
        internal System.Windows.Forms.Label lblToolStatus;
        internal System.Windows.Forms.Button btnSetTools;
        internal System.Windows.Forms.Button btnRefreshDevices;
        internal System.Windows.Forms.Label lblDevice;
        internal System.Windows.Forms.ComboBox cboDevices;
        internal System.Windows.Forms.Button btnAdbDevices;
        internal System.Windows.Forms.Button btnFastbootDevices;
        internal System.Windows.Forms.TabControl tabActions;
        internal System.Windows.Forms.TabPage tabAdb;
        internal System.Windows.Forms.FlowLayoutPanel flpAdb;
        internal System.Windows.Forms.Button btnAdbReboot;
        internal System.Windows.Forms.Button btnAdbRecovery;
        internal System.Windows.Forms.Button btnAdbBootloader;
        internal System.Windows.Forms.Button btnAdbDownload;
        internal System.Windows.Forms.Button btnAdbEdl;
        internal System.Windows.Forms.Button btnAdbInstall;
        internal System.Windows.Forms.Button btnAdbUninstall;
        internal System.Windows.Forms.Button btnAdbPush;
        internal System.Windows.Forms.Button btnAdbPull;
        internal System.Windows.Forms.Button btnAdbSideload;
        internal System.Windows.Forms.Button btnAdbLogcat;
        internal System.Windows.Forms.Button btnAdbScreencap;
        internal System.Windows.Forms.Button btnAdbShell;
        internal System.Windows.Forms.Button btnAdbGetprop;
        internal System.Windows.Forms.Button btnAdbPackages;
        internal System.Windows.Forms.Button btnAdbBattery;
        internal System.Windows.Forms.Button btnAdbScreenSize;
        internal System.Windows.Forms.Button btnAdbTcpip;
        internal System.Windows.Forms.Button btnAdbConnect;
        internal System.Windows.Forms.Button btnAdbBackup;
        internal System.Windows.Forms.Button btnAdbRestore;
        internal System.Windows.Forms.Button btnAdbKillServer;
        internal System.Windows.Forms.Button btnAdbStartServer;
        internal System.Windows.Forms.TabPage tabFastboot;
        internal System.Windows.Forms.FlowLayoutPanel flpFastboot;
        internal System.Windows.Forms.Button btnFbGetvar;
        internal System.Windows.Forms.Button btnFbUnlock;
        internal System.Windows.Forms.Button btnFbOemUnlock;
        internal System.Windows.Forms.Button btnFbLock;
        internal System.Windows.Forms.Button btnFbReboot;
        internal System.Windows.Forms.Button btnFbBootloader;
        internal System.Windows.Forms.Button btnFbRecovery;
        internal System.Windows.Forms.Button btnFbFastbootd;
        internal System.Windows.Forms.Button btnFbBootImg;
        internal System.Windows.Forms.Button btnFbFlashPartition;
        internal System.Windows.Forms.Button btnFbFlashBoot;
        internal System.Windows.Forms.Button btnFbFlashRecovery;
        internal System.Windows.Forms.Button btnFbErase;
        internal System.Windows.Forms.Button btnFbFormat;
        internal System.Windows.Forms.Button btnFbActiveA;
        internal System.Windows.Forms.Button btnFbActiveB;
        internal System.Windows.Forms.Button btnFbWipe;
        internal System.Windows.Forms.Button btnFbContinue;
        internal System.Windows.Forms.TabPage tabDownload;
        internal System.Windows.Forms.FlowLayoutPanel flpDownload;
        internal System.Windows.Forms.Button btnDlSamsung;
        internal System.Windows.Forms.Button btnDlEdlAdb;
        internal System.Windows.Forms.Button btnDlEdlFastboot;
        internal System.Windows.Forms.Button btnHeimdallDetect;
        internal System.Windows.Forms.Button btnHeimdallPit;
        internal System.Windows.Forms.Button btnHeimdallFlash;
        internal System.Windows.Forms.Button btnRecReboot;
        internal System.Windows.Forms.Button btnRecSideload;
        internal System.Windows.Forms.Label lblVendorNote;
        internal System.Windows.Forms.TextBox txtConsole;
        internal System.Windows.Forms.TableLayoutPanel tlpCommandBar;
        internal System.Windows.Forms.TextBox txtCommand;
        internal System.Windows.Forms.Button btnRun;
        internal System.Windows.Forms.Button btnStop;
        internal System.Windows.Forms.Button btnClear;
    }
}
