// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules.Views
{
    partial class LicenseView
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle licExpiryFormat = new System.Windows.Forms.DataGridViewCellStyle();
            licExpiryFormat.Format = "yyyy-MM-dd";
            licExpiryFormat.NullValue = "";
            System.Windows.Forms.DataGridViewCellStyle licGridAlt = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle licGridHeader = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle licGridCell = new System.Windows.Forms.DataGridViewCellStyle();
            licGridAlt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(19)))), ((int)(((byte)(30)))));
            licGridHeader.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            licGridHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            licGridHeader.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F, System.Drawing.FontStyle.Bold);
            licGridHeader.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            licGridHeader.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            licGridHeader.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            licGridHeader.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            licGridCell.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            licGridCell.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(21)))), ((int)(((byte)(33)))));
            licGridCell.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            licGridCell.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(48)))), ((int)(((byte)(65)))));
            licGridCell.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            licGridCell.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.tlpRoot = new System.Windows.Forms.TableLayoutPanel();
            this.flpBar = new System.Windows.Forms.FlowLayoutPanel();
            this.lblSearch = new System.Windows.Forms.Label();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.cboCategory = new System.Windows.Forms.ComboBox();
            this.cboStatus = new System.Windows.Forms.ComboBox();
            this.btnAdd = new System.Windows.Forms.Button();
            this.btnEdit = new System.Windows.Forms.Button();
            this.btnDuplicate = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.btnCheckExpiries = new System.Windows.Forms.Button();
            this.btnStats = new System.Windows.Forms.Button();
            this.btnExportCsv = new System.Windows.Forms.Button();
            this.btnImportCsv = new System.Windows.Forms.Button();
            this.btnOpenPortal = new System.Windows.Forms.Button();
            this.btnOpenFolder = new System.Windows.Forms.Button();
            this.grdLicenses = new System.Windows.Forms.DataGridView();
            this.colTool = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colVendor = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colCategory = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colStatus = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colCredits = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colExpires = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colHardwareId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colNotes = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblCount = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.grdLicenses)).BeginInit();
            this.tlpRoot.SuspendLayout();
            this.flpBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpRoot
            // 
            this.tlpRoot.Controls.Add(this.flpBar, 0, 0);
            this.tlpRoot.Controls.Add(this.grdLicenses, 0, 1);
            this.tlpRoot.Controls.Add(this.lblCount, 0, 2);
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRoot.ColumnCount = 1;
            this.tlpRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRoot.RowCount = 3;
            this.tlpRoot.Padding = new System.Windows.Forms.Padding(8);
            this.tlpRoot.Name = "tlpRoot";
            // 
            // flpBar
            // 
            this.flpBar.Controls.Add(this.lblSearch);
            this.flpBar.Controls.Add(this.txtSearch);
            this.flpBar.Controls.Add(this.cboCategory);
            this.flpBar.Controls.Add(this.cboStatus);
            this.flpBar.Controls.Add(this.btnAdd);
            this.flpBar.Controls.Add(this.btnEdit);
            this.flpBar.Controls.Add(this.btnDuplicate);
            this.flpBar.Controls.Add(this.btnDelete);
            this.flpBar.Controls.Add(this.btnCheckExpiries);
            this.flpBar.Controls.Add(this.btnStats);
            this.flpBar.Controls.Add(this.btnExportCsv);
            this.flpBar.Controls.Add(this.btnImportCsv);
            this.flpBar.Controls.Add(this.btnOpenPortal);
            this.flpBar.Controls.Add(this.btnOpenFolder);
            this.flpBar.AutoSize = true;
            this.flpBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpBar.Name = "flpBar";
            // 
            // lblSearch
            // 
            this.lblSearch.AutoSize = true;
            this.lblSearch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblSearch.Text = "Search:";
            this.lblSearch.Margin = new System.Windows.Forms.Padding(0, 6, 4, 0);
            this.lblSearch.Name = "lblSearch";
            // 
            // txtSearch
            // 
            this.txtSearch.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.txtSearch.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtSearch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtSearch.Size = new System.Drawing.Size(180, 24);
            this.txtSearch.Name = "txtSearch";
            // 
            // cboCategory
            // 
            this.cboCategory.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboCategory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboCategory.FormattingEnabled = true;
            this.cboCategory.Size = new System.Drawing.Size(120, 25);
            this.cboCategory.Items.AddRange(new object[] {
            "All categories",
            "Forensic",
            "Servicing",
            "FRP",
            "Flashing",
            "Other"});
            this.cboCategory.Name = "cboCategory";
            // 
            // cboStatus
            // 
            this.cboStatus.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboStatus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboStatus.FormattingEnabled = true;
            this.cboStatus.Size = new System.Drawing.Size(110, 25);
            this.cboStatus.Items.AddRange(new object[] {
            "All statuses",
            "Active",
            "Expired",
            "Suspended"});
            this.cboStatus.Name = "cboStatus";
            // 
            // btnAdd
            // 
            this.btnAdd.AutoSize = true;
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnAdd.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnAdd.Padding = new System.Windows.Forms.Padding(0);
            this.btnAdd.Text = "Add";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnAdd.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnEdit
            // 
            this.btnEdit.AutoSize = true;
            this.btnEdit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnEdit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnEdit.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnEdit.Padding = new System.Windows.Forms.Padding(0);
            this.btnEdit.Text = "Edit";
            this.btnEdit.UseVisualStyleBackColor = false;
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnEdit.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnDuplicate
            // 
            this.btnDuplicate.AutoSize = true;
            this.btnDuplicate.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnDuplicate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDuplicate.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnDuplicate.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnDuplicate.Padding = new System.Windows.Forms.Padding(0);
            this.btnDuplicate.Text = "Duplicate";
            this.btnDuplicate.UseVisualStyleBackColor = false;
            this.btnDuplicate.Name = "btnDuplicate";
            this.btnDuplicate.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnDuplicate.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnDelete
            // 
            this.btnDelete.AutoSize = true;
            this.btnDelete.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnDelete.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnDelete.Padding = new System.Windows.Forms.Padding(0);
            this.btnDelete.Text = "Delete";
            this.btnDelete.UseVisualStyleBackColor = false;
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnDelete.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnCheckExpiries
            // 
            this.btnCheckExpiries.AutoSize = true;
            this.btnCheckExpiries.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnCheckExpiries.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCheckExpiries.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnCheckExpiries.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnCheckExpiries.Padding = new System.Windows.Forms.Padding(0);
            this.btnCheckExpiries.Text = "Check expiries";
            this.btnCheckExpiries.UseVisualStyleBackColor = false;
            this.btnCheckExpiries.Name = "btnCheckExpiries";
            this.btnCheckExpiries.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnCheckExpiries.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnStats
            // 
            this.btnStats.AutoSize = true;
            this.btnStats.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnStats.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStats.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnStats.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnStats.Padding = new System.Windows.Forms.Padding(0);
            this.btnStats.Text = "Stats";
            this.btnStats.UseVisualStyleBackColor = false;
            this.btnStats.Name = "btnStats";
            this.btnStats.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnStats.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnExportCsv
            // 
            this.btnExportCsv.AutoSize = true;
            this.btnExportCsv.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnExportCsv.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExportCsv.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnExportCsv.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnExportCsv.Padding = new System.Windows.Forms.Padding(0);
            this.btnExportCsv.Text = "Export CSV";
            this.btnExportCsv.UseVisualStyleBackColor = false;
            this.btnExportCsv.Name = "btnExportCsv";
            this.btnExportCsv.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnExportCsv.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnImportCsv
            // 
            this.btnImportCsv.AutoSize = true;
            this.btnImportCsv.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnImportCsv.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnImportCsv.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnImportCsv.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnImportCsv.Padding = new System.Windows.Forms.Padding(0);
            this.btnImportCsv.Text = "Import CSV";
            this.btnImportCsv.UseVisualStyleBackColor = false;
            this.btnImportCsv.Name = "btnImportCsv";
            this.btnImportCsv.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnImportCsv.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnOpenPortal
            // 
            this.btnOpenPortal.AutoSize = true;
            this.btnOpenPortal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnOpenPortal.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnOpenPortal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnOpenPortal.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnOpenPortal.Padding = new System.Windows.Forms.Padding(0);
            this.btnOpenPortal.Text = "Open portal";
            this.btnOpenPortal.UseVisualStyleBackColor = false;
            this.btnOpenPortal.Name = "btnOpenPortal";
            this.btnOpenPortal.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnOpenPortal.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnOpenFolder
            // 
            this.btnOpenFolder.AutoSize = true;
            this.btnOpenFolder.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnOpenFolder.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnOpenFolder.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnOpenFolder.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnOpenFolder.Padding = new System.Windows.Forms.Padding(0);
            this.btnOpenFolder.Text = "Open folder";
            this.btnOpenFolder.UseVisualStyleBackColor = false;
            this.btnOpenFolder.Name = "btnOpenFolder";
            this.btnOpenFolder.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnOpenFolder.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // grdLicenses
            // 
            this.grdLicenses.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.colTool,
            this.colVendor,
            this.colCategory,
            this.colType,
            this.colStatus,
            this.colCredits,
            this.colExpires,
            this.colHardwareId,
            this.colNotes});
            this.grdLicenses.AlternatingRowsDefaultCellStyle = licGridAlt;
            this.grdLicenses.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(21)))), ((int)(((byte)(33)))));
            this.grdLicenses.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.grdLicenses.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.grdLicenses.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.grdLicenses.ColumnHeadersDefaultCellStyle = licGridHeader;
            this.grdLicenses.ColumnHeadersHeight = 38;
            this.grdLicenses.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.grdLicenses.DefaultCellStyle = licGridCell;
            this.grdLicenses.EnableHeadersVisualStyles = false;
            this.grdLicenses.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            this.grdLicenses.RowHeadersVisible = false;
            this.grdLicenses.AllowUserToAddRows = false;
            this.grdLicenses.AllowUserToDeleteRows = false;
            this.grdLicenses.AllowUserToResizeRows = false;
            this.grdLicenses.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grdLicenses.ReadOnly = true;
            this.grdLicenses.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grdLicenses.MultiSelect = false;
            this.grdLicenses.Name = "grdLicenses";
            this.grdLicenses.RowTemplate.Height = 30;
            // 
            // colTool
            // 
            this.colTool.HeaderText = "Tool";
            this.colTool.DataPropertyName = "Tool";
            this.colTool.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colTool.Width = 130;
            this.colTool.ReadOnly = true;
            this.colTool.Name = "colTool";
            // 
            // colVendor
            // 
            this.colVendor.HeaderText = "Vendor";
            this.colVendor.DataPropertyName = "Vendor";
            this.colVendor.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colVendor.Width = 100;
            this.colVendor.ReadOnly = true;
            this.colVendor.Name = "colVendor";
            // 
            // colCategory
            // 
            this.colCategory.HeaderText = "Category";
            this.colCategory.DataPropertyName = "Category";
            this.colCategory.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colCategory.Width = 80;
            this.colCategory.ReadOnly = true;
            this.colCategory.Name = "colCategory";
            // 
            // colType
            // 
            this.colType.HeaderText = "Type";
            this.colType.DataPropertyName = "LicenseType";
            this.colType.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colType.Width = 90;
            this.colType.ReadOnly = true;
            this.colType.Name = "colType";
            // 
            // colStatus
            // 
            this.colStatus.HeaderText = "Status";
            this.colStatus.DataPropertyName = "Status";
            this.colStatus.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colStatus.Width = 70;
            this.colStatus.ReadOnly = true;
            this.colStatus.Name = "colStatus";
            // 
            // colCredits
            // 
            this.colCredits.HeaderText = "Credits";
            this.colCredits.DataPropertyName = "Credits";
            this.colCredits.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colCredits.Width = 60;
            this.colCredits.ReadOnly = true;
            this.colCredits.Name = "colCredits";
            // 
            // colExpires
            // 
            this.colExpires.HeaderText = "Expires";
            this.colExpires.DataPropertyName = "ExpiryDate";
            this.colExpires.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colExpires.Width = 90;
            this.colExpires.DefaultCellStyle = licExpiryFormat;
            this.colExpires.ReadOnly = true;
            this.colExpires.Name = "colExpires";
            // 
            // colHardwareId
            // 
            this.colHardwareId.HeaderText = "Dongle/HW ID";
            this.colHardwareId.DataPropertyName = "HardwareId";
            this.colHardwareId.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colHardwareId.Width = 120;
            this.colHardwareId.ReadOnly = true;
            this.colHardwareId.Name = "colHardwareId";
            // 
            // colNotes
            // 
            this.colNotes.HeaderText = "Notes";
            this.colNotes.DataPropertyName = "Notes";
            this.colNotes.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colNotes.Width = 180;
            this.colNotes.ReadOnly = true;
            this.colNotes.Name = "colNotes";
            // 
            // lblCount
            // 
            this.lblCount.AutoSize = true;
            this.lblCount.ForeColor = System.Drawing.Color.DimGray;
            this.lblCount.Text = "";
            this.lblCount.Margin = new System.Windows.Forms.Padding(2, 4, 0, 0);
            this.lblCount.Name = "lblCount";
            // 
            // LicenseView
            // 
            this.Controls.Add(this.tlpRoot);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.Size = new System.Drawing.Size(1000, 680);
            this.Name = "LicenseView";
            ((System.ComponentModel.ISupportInitialize)(this.grdLicenses)).EndInit();
            this.flpBar.ResumeLayout(false);
            this.flpBar.PerformLayout();
            this.tlpRoot.ResumeLayout(false);
            this.tlpRoot.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.TableLayoutPanel tlpRoot;
        internal System.Windows.Forms.FlowLayoutPanel flpBar;
        internal System.Windows.Forms.Label lblSearch;
        internal System.Windows.Forms.TextBox txtSearch;
        internal System.Windows.Forms.ComboBox cboCategory;
        internal System.Windows.Forms.ComboBox cboStatus;
        internal System.Windows.Forms.Button btnAdd;
        internal System.Windows.Forms.Button btnEdit;
        internal System.Windows.Forms.Button btnDuplicate;
        internal System.Windows.Forms.Button btnDelete;
        internal System.Windows.Forms.Button btnCheckExpiries;
        internal System.Windows.Forms.Button btnStats;
        internal System.Windows.Forms.Button btnExportCsv;
        internal System.Windows.Forms.Button btnImportCsv;
        internal System.Windows.Forms.Button btnOpenPortal;
        internal System.Windows.Forms.Button btnOpenFolder;
        internal System.Windows.Forms.DataGridView grdLicenses;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colTool;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colVendor;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colCategory;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colType;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colStatus;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colCredits;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colExpires;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colHardwareId;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colNotes;
        internal System.Windows.Forms.Label lblCount;
    }
}
