// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules.Views
{
    partial class LiveCoachView
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tlpRoot = new System.Windows.Forms.TableLayoutPanel();
            this.picPreview = new System.Windows.Forms.PictureBox();
            this.tlpRight = new System.Windows.Forms.TableLayoutPanel();
            this.flpBar = new System.Windows.Forms.FlowLayoutPanel();
            this.cboKind = new System.Windows.Forms.ComboBox();
            this.cboApp = new System.Windows.Forms.ComboBox();
            this.lblPhoneIp = new System.Windows.Forms.Label();
            this.txtPhoneIp = new System.Windows.Forms.TextBox();
            this.btnStart = new System.Windows.Forms.Button();
            this.btnStop = new System.Windows.Forms.Button();
            this.btnQuickStart = new System.Windows.Forms.Button();
            this.lstLog = new System.Windows.Forms.ListBox();
            ((System.ComponentModel.ISupportInitialize)(this.picPreview)).BeginInit();
            this.tlpRoot.SuspendLayout();
            this.tlpRight.SuspendLayout();
            this.flpBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpRoot
            // 
            this.tlpRoot.Controls.Add(this.picPreview, 0, 0);
            this.tlpRoot.Controls.Add(this.tlpRight, 1, 0);
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRoot.ColumnCount = 2;
            this.tlpRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRoot.RowCount = 1;
            this.tlpRoot.Padding = new System.Windows.Forms.Padding(8);
            this.tlpRoot.Name = "tlpRoot";
            // 
            // picPreview
            // 
            this.picPreview.BackColor = System.Drawing.Color.Black;
            this.picPreview.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picPreview.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picPreview.TabStop = false;
            this.picPreview.Name = "picPreview";
            // 
            // tlpRight
            // 
            this.tlpRight.Controls.Add(this.flpBar, 0, 0);
            this.tlpRight.Controls.Add(this.lstLog, 0, 1);
            this.tlpRight.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRight.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRight.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRight.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRight.ColumnCount = 1;
            this.tlpRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRight.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRight.RowCount = 2;
            this.tlpRight.Name = "tlpRight";
            // 
            // flpBar
            // 
            this.flpBar.Controls.Add(this.cboKind);
            this.flpBar.Controls.Add(this.cboApp);
            this.flpBar.Controls.Add(this.lblPhoneIp);
            this.flpBar.Controls.Add(this.txtPhoneIp);
            this.flpBar.Controls.Add(this.btnStart);
            this.flpBar.Controls.Add(this.btnStop);
            this.flpBar.Controls.Add(this.btnQuickStart);
            this.flpBar.AutoSize = true;
            this.flpBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpBar.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpBar.Name = "flpBar";
            // 
            // cboKind
            // 
            this.cboKind.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboKind.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKind.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboKind.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboKind.FormattingEnabled = true;
            this.cboKind.Size = new System.Drawing.Size(130, 25);
            this.cboKind.Items.AddRange(new object[] {
            "Local camera",
            "Phone camera"});
            this.cboKind.Name = "cboKind";
            // 
            // cboApp
            // 
            this.cboApp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboApp.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboApp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboApp.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboApp.FormattingEnabled = true;
            this.cboApp.Enabled = false;
            this.cboApp.Size = new System.Drawing.Size(110, 25);
            this.cboApp.Items.AddRange(new object[] {
            "IP Webcam",
            "DroidCam",
            "RTSP",
            "Full URL"});
            this.cboApp.Name = "cboApp";
            // 
            // lblPhoneIp
            // 
            this.lblPhoneIp.AutoSize = true;
            this.lblPhoneIp.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblPhoneIp.Text = "Phone IP:";
            this.lblPhoneIp.Padding = new System.Windows.Forms.Padding(6, 6, 0, 0);
            this.lblPhoneIp.Name = "lblPhoneIp";
            // 
            // txtPhoneIp
            // 
            this.txtPhoneIp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.txtPhoneIp.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPhoneIp.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtPhoneIp.Enabled = false;
            this.txtPhoneIp.Size = new System.Drawing.Size(150, 24);
            this.txtPhoneIp.Text = "192.168.1.";
            this.txtPhoneIp.Name = "txtPhoneIp";
            // 
            // btnStart
            // 
            this.btnStart.AutoSize = true;
            this.btnStart.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStart.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnStart.Margin = new System.Windows.Forms.Padding(3);
            this.btnStart.Padding = new System.Windows.Forms.Padding(0);
            this.btnStart.Text = "Start watching";
            this.btnStart.UseVisualStyleBackColor = false;
            this.btnStart.Name = "btnStart";
            this.btnStart.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnStart.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnStop
            // 
            this.btnStop.AutoSize = true;
            this.btnStop.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnStop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnStop.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnStop.Margin = new System.Windows.Forms.Padding(3);
            this.btnStop.Padding = new System.Windows.Forms.Padding(0);
            this.btnStop.Text = "Stop";
            this.btnStop.UseVisualStyleBackColor = false;
            this.btnStop.Name = "btnStop";
            this.btnStop.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnStop.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnQuickStart
            // 
            this.btnQuickStart.AutoSize = true;
            this.btnQuickStart.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnQuickStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnQuickStart.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnQuickStart.Margin = new System.Windows.Forms.Padding(3);
            this.btnQuickStart.Padding = new System.Windows.Forms.Padding(0);
            this.btnQuickStart.Text = "Quick start";
            this.btnQuickStart.UseVisualStyleBackColor = false;
            this.btnQuickStart.Name = "btnQuickStart";
            this.btnQuickStart.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnQuickStart.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // lstLog
            // 
            this.lstLog.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.lstLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstLog.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.lstLog.FormattingEnabled = true;
            this.lstLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstLog.Font = new System.Drawing.Font("Consolas", 9F);
            this.lstLog.HorizontalScrollbar = true;
            this.lstLog.IntegralHeight = false;
            this.lstLog.Name = "lstLog";
            // 
            // LiveCoachView
            // 
            this.Controls.Add(this.tlpRoot);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.Size = new System.Drawing.Size(1000, 680);
            this.Name = "LiveCoachView";
            ((System.ComponentModel.ISupportInitialize)(this.picPreview)).EndInit();
            this.flpBar.ResumeLayout(false);
            this.flpBar.PerformLayout();
            this.tlpRight.ResumeLayout(false);
            this.tlpRight.PerformLayout();
            this.tlpRoot.ResumeLayout(false);
            this.tlpRoot.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.TableLayoutPanel tlpRoot;
        internal System.Windows.Forms.PictureBox picPreview;
        internal System.Windows.Forms.TableLayoutPanel tlpRight;
        internal System.Windows.Forms.FlowLayoutPanel flpBar;
        internal System.Windows.Forms.ComboBox cboKind;
        internal System.Windows.Forms.ComboBox cboApp;
        internal System.Windows.Forms.Label lblPhoneIp;
        internal System.Windows.Forms.TextBox txtPhoneIp;
        internal System.Windows.Forms.Button btnStart;
        internal System.Windows.Forms.Button btnStop;
        internal System.Windows.Forms.Button btnQuickStart;
        internal System.Windows.Forms.ListBox lstLog;
    }
}
