// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules.Views
{
    partial class LogView
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle logTimeFormat = new System.Windows.Forms.DataGridViewCellStyle();
            logTimeFormat.Format = "yyyy-MM-dd HH:mm:ss";
            System.Windows.Forms.DataGridViewCellStyle logGridAlt = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle logGridHeader = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle logGridCell = new System.Windows.Forms.DataGridViewCellStyle();
            logGridAlt.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(19)))), ((int)(((byte)(30)))));
            logGridHeader.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            logGridHeader.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            logGridHeader.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F, System.Drawing.FontStyle.Bold);
            logGridHeader.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            logGridHeader.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            logGridHeader.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            logGridHeader.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            logGridCell.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            logGridCell.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(21)))), ((int)(((byte)(33)))));
            logGridCell.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            logGridCell.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(48)))), ((int)(((byte)(65)))));
            logGridCell.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            logGridCell.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.tlpRoot = new System.Windows.Forms.TableLayoutPanel();
            this.flpBar = new System.Windows.Forms.FlowLayoutPanel();
            this.lblSearch = new System.Windows.Forms.Label();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.lblSource = new System.Windows.Forms.Label();
            this.cboSource = new System.Windows.Forms.ComboBox();
            this.lblLevel = new System.Windows.Forms.Label();
            this.cboLevel = new System.Windows.Forms.ComboBox();
            this.chkLive = new System.Windows.Forms.CheckBox();
            this.btnRefresh = new System.Windows.Forms.Button();
            this.btnVerify = new System.Windows.Forms.Button();
            this.btnSaveView = new System.Windows.Forms.Button();
            this.btnLoadFile = new System.Windows.Forms.Button();
            this.btnOpenFolder = new System.Windows.Forms.Button();
            this.btnArchiveClear = new System.Windows.Forms.Button();
            this.grdLog = new System.Windows.Forms.DataGridView();
            this.colTime = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colSource = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colLevel = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMessage = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblSummary = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.grdLog)).BeginInit();
            this.tlpRoot.SuspendLayout();
            this.flpBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpRoot
            // 
            this.tlpRoot.Controls.Add(this.flpBar, 0, 0);
            this.tlpRoot.Controls.Add(this.grdLog, 0, 1);
            this.tlpRoot.Controls.Add(this.lblSummary, 0, 2);
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRoot.ColumnCount = 1;
            this.tlpRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRoot.RowCount = 3;
            this.tlpRoot.Padding = new System.Windows.Forms.Padding(8);
            this.tlpRoot.Name = "tlpRoot";
            // 
            // flpBar
            // 
            this.flpBar.Controls.Add(this.lblSearch);
            this.flpBar.Controls.Add(this.txtSearch);
            this.flpBar.Controls.Add(this.lblSource);
            this.flpBar.Controls.Add(this.cboSource);
            this.flpBar.Controls.Add(this.lblLevel);
            this.flpBar.Controls.Add(this.cboLevel);
            this.flpBar.Controls.Add(this.chkLive);
            this.flpBar.Controls.Add(this.btnRefresh);
            this.flpBar.Controls.Add(this.btnVerify);
            this.flpBar.Controls.Add(this.btnSaveView);
            this.flpBar.Controls.Add(this.btnLoadFile);
            this.flpBar.Controls.Add(this.btnOpenFolder);
            this.flpBar.Controls.Add(this.btnArchiveClear);
            this.flpBar.AutoSize = true;
            this.flpBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpBar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpBar.Name = "flpBar";
            // 
            // lblSearch
            // 
            this.lblSearch.AutoSize = true;
            this.lblSearch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblSearch.Text = "Search:";
            this.lblSearch.Margin = new System.Windows.Forms.Padding(0, 6, 4, 0);
            this.lblSearch.Name = "lblSearch";
            // 
            // txtSearch
            // 
            this.txtSearch.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.txtSearch.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtSearch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtSearch.Size = new System.Drawing.Size(200, 24);
            this.txtSearch.Name = "txtSearch";
            // 
            // lblSource
            // 
            this.lblSource.AutoSize = true;
            this.lblSource.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblSource.Text = "Source:";
            this.lblSource.Margin = new System.Windows.Forms.Padding(8, 6, 4, 0);
            this.lblSource.Name = "lblSource";
            // 
            // cboSource
            // 
            this.cboSource.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboSource.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboSource.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboSource.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboSource.FormattingEnabled = true;
            this.cboSource.Size = new System.Drawing.Size(120, 25);
            this.cboSource.Name = "cboSource";
            // 
            // lblLevel
            // 
            this.lblLevel.AutoSize = true;
            this.lblLevel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblLevel.Text = "Level:";
            this.lblLevel.Margin = new System.Windows.Forms.Padding(8, 6, 4, 0);
            this.lblLevel.Name = "lblLevel";
            // 
            // cboLevel
            // 
            this.cboLevel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboLevel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLevel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboLevel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboLevel.FormattingEnabled = true;
            this.cboLevel.Size = new System.Drawing.Size(100, 25);
            this.cboLevel.Name = "cboLevel";
            // 
            // chkLive
            // 
            this.chkLive.AutoSize = true;
            this.chkLive.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.chkLive.Text = "Live";
            this.chkLive.UseVisualStyleBackColor = false;
            this.chkLive.Checked = true;
            this.chkLive.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkLive.Margin = new System.Windows.Forms.Padding(8, 6, 8, 0);
            this.chkLive.Name = "chkLive";
            // 
            // btnRefresh
            // 
            this.btnRefresh.AutoSize = true;
            this.btnRefresh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRefresh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRefresh.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRefresh.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnRefresh.Padding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.UseVisualStyleBackColor = false;
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRefresh.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnVerify
            // 
            this.btnVerify.AutoSize = true;
            this.btnVerify.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnVerify.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnVerify.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnVerify.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnVerify.Padding = new System.Windows.Forms.Padding(0);
            this.btnVerify.Text = "Verify";
            this.btnVerify.UseVisualStyleBackColor = false;
            this.btnVerify.Name = "btnVerify";
            this.btnVerify.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnVerify.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnSaveView
            // 
            this.btnSaveView.AutoSize = true;
            this.btnSaveView.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnSaveView.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSaveView.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnSaveView.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnSaveView.Padding = new System.Windows.Forms.Padding(0);
            this.btnSaveView.Text = "Save view…";
            this.btnSaveView.UseVisualStyleBackColor = false;
            this.btnSaveView.Name = "btnSaveView";
            this.btnSaveView.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnSaveView.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnLoadFile
            // 
            this.btnLoadFile.AutoSize = true;
            this.btnLoadFile.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnLoadFile.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLoadFile.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnLoadFile.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnLoadFile.Padding = new System.Windows.Forms.Padding(0);
            this.btnLoadFile.Text = "Load file…";
            this.btnLoadFile.UseVisualStyleBackColor = false;
            this.btnLoadFile.Name = "btnLoadFile";
            this.btnLoadFile.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnLoadFile.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnOpenFolder
            // 
            this.btnOpenFolder.AutoSize = true;
            this.btnOpenFolder.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnOpenFolder.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnOpenFolder.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnOpenFolder.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnOpenFolder.Padding = new System.Windows.Forms.Padding(0);
            this.btnOpenFolder.Text = "Open folder";
            this.btnOpenFolder.UseVisualStyleBackColor = false;
            this.btnOpenFolder.Name = "btnOpenFolder";
            this.btnOpenFolder.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnOpenFolder.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // btnArchiveClear
            // 
            this.btnArchiveClear.AutoSize = true;
            this.btnArchiveClear.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnArchiveClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnArchiveClear.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnArchiveClear.Margin = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.btnArchiveClear.Padding = new System.Windows.Forms.Padding(0);
            this.btnArchiveClear.Text = "Archive & clear";
            this.btnArchiveClear.UseVisualStyleBackColor = false;
            this.btnArchiveClear.Name = "btnArchiveClear";
            this.btnArchiveClear.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnArchiveClear.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // grdLog
            // 
            this.grdLog.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.colTime,
            this.colSource,
            this.colLevel,
            this.colMessage});
            this.grdLog.AlternatingRowsDefaultCellStyle = logGridAlt;
            this.grdLog.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(21)))), ((int)(((byte)(33)))));
            this.grdLog.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.grdLog.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.grdLog.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.grdLog.ColumnHeadersDefaultCellStyle = logGridHeader;
            this.grdLog.ColumnHeadersHeight = 38;
            this.grdLog.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.grdLog.DefaultCellStyle = logGridCell;
            this.grdLog.EnableHeadersVisualStyles = false;
            this.grdLog.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            this.grdLog.RowHeadersVisible = false;
            this.grdLog.AllowUserToAddRows = false;
            this.grdLog.AllowUserToDeleteRows = false;
            this.grdLog.AllowUserToResizeRows = false;
            this.grdLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grdLog.ReadOnly = true;
            this.grdLog.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grdLog.Font = new System.Drawing.Font("Consolas", 9F);
            this.grdLog.Name = "grdLog";
            this.grdLog.RowTemplate.Height = 30;
            // 
            // colTime
            // 
            this.colTime.HeaderText = "Time";
            this.colTime.DataPropertyName = "Time";
            this.colTime.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colTime.Width = 140;
            this.colTime.DefaultCellStyle = logTimeFormat;
            this.colTime.ReadOnly = true;
            this.colTime.Name = "colTime";
            // 
            // colSource
            // 
            this.colSource.HeaderText = "Source";
            this.colSource.DataPropertyName = "Source";
            this.colSource.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colSource.Width = 90;
            this.colSource.ReadOnly = true;
            this.colSource.Name = "colSource";
            // 
            // colLevel
            // 
            this.colLevel.HeaderText = "Level";
            this.colLevel.DataPropertyName = "Level";
            this.colLevel.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.colLevel.Width = 70;
            this.colLevel.ReadOnly = true;
            this.colLevel.Name = "colLevel";
            // 
            // colMessage
            // 
            this.colMessage.HeaderText = "Message";
            this.colMessage.DataPropertyName = "Message";
            this.colMessage.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.colMessage.ReadOnly = true;
            this.colMessage.Name = "colMessage";
            // 
            // lblSummary
            // 
            this.lblSummary.AutoSize = true;
            this.lblSummary.ForeColor = System.Drawing.Color.DimGray;
            this.lblSummary.Text = "";
            this.lblSummary.Margin = new System.Windows.Forms.Padding(2, 4, 0, 0);
            this.lblSummary.Name = "lblSummary";
            // 
            // LogView
            // 
            this.Controls.Add(this.tlpRoot);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.Size = new System.Drawing.Size(1000, 680);
            this.Name = "LogView";
            ((System.ComponentModel.ISupportInitialize)(this.grdLog)).EndInit();
            this.flpBar.ResumeLayout(false);
            this.flpBar.PerformLayout();
            this.tlpRoot.ResumeLayout(false);
            this.tlpRoot.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.TableLayoutPanel tlpRoot;
        internal System.Windows.Forms.FlowLayoutPanel flpBar;
        internal System.Windows.Forms.Label lblSearch;
        internal System.Windows.Forms.TextBox txtSearch;
        internal System.Windows.Forms.Label lblSource;
        internal System.Windows.Forms.ComboBox cboSource;
        internal System.Windows.Forms.Label lblLevel;
        internal System.Windows.Forms.ComboBox cboLevel;
        internal System.Windows.Forms.CheckBox chkLive;
        internal System.Windows.Forms.Button btnRefresh;
        internal System.Windows.Forms.Button btnVerify;
        internal System.Windows.Forms.Button btnSaveView;
        internal System.Windows.Forms.Button btnLoadFile;
        internal System.Windows.Forms.Button btnOpenFolder;
        internal System.Windows.Forms.Button btnArchiveClear;
        internal System.Windows.Forms.DataGridView grdLog;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colTime;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colSource;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colLevel;
        internal System.Windows.Forms.DataGridViewTextBoxColumn colMessage;
        internal System.Windows.Forms.Label lblSummary;
    }
}
