// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules.Views
{
    partial class UsbTriggerView
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tlpRoot = new System.Windows.Forms.TableLayoutPanel();
            this.flpAdminBanner = new System.Windows.Forms.FlowLayoutPanel();
            this.lblAdminWarning = new System.Windows.Forms.Label();
            this.btnRestartAdmin = new System.Windows.Forms.Button();
            this.lblDevice = new System.Windows.Forms.Label();
            this.flpDeviceRow = new System.Windows.Forms.FlowLayoutPanel();
            this.cboDevices = new System.Windows.Forms.ComboBox();
            this.btnRefresh = new System.Windows.Forms.Button();
            this.flpCountdownRow = new System.Windows.Forms.FlowLayoutPanel();
            this.lblCountdown = new System.Windows.Forms.Label();
            this.nudSeconds = new System.Windows.Forms.NumericUpDown();
            this.lblTimeLeftCaption = new System.Windows.Forms.Label();
            this.lblTimeLeft = new System.Windows.Forms.Label();
            this.flpActionRow = new System.Windows.Forms.FlowLayoutPanel();
            this.btnToggle = new System.Windows.Forms.Button();
            this.btnReenableAll = new System.Windows.Forms.Button();
            this.flpVoiceRow = new System.Windows.Forms.FlowLayoutPanel();
            this.chkVoice = new System.Windows.Forms.CheckBox();
            this.lblSayAny = new System.Windows.Forms.Label();
            this.txtPhrases = new System.Windows.Forms.TextBox();
            this.lblMinConfidence = new System.Windows.Forms.Label();
            this.nudConfidence = new System.Windows.Forms.NumericUpDown();
            this.lblHotkeyHint = new System.Windows.Forms.Label();
            this.txtLog = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.nudSeconds)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudConfidence)).BeginInit();
            this.tlpRoot.SuspendLayout();
            this.flpAdminBanner.SuspendLayout();
            this.flpDeviceRow.SuspendLayout();
            this.flpCountdownRow.SuspendLayout();
            this.flpActionRow.SuspendLayout();
            this.flpVoiceRow.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpRoot
            // 
            this.tlpRoot.Controls.Add(this.flpAdminBanner, 0, 0);
            this.tlpRoot.Controls.Add(this.lblDevice, 0, 1);
            this.tlpRoot.Controls.Add(this.flpDeviceRow, 0, 2);
            this.tlpRoot.Controls.Add(this.flpCountdownRow, 0, 3);
            this.tlpRoot.Controls.Add(this.flpActionRow, 0, 4);
            this.tlpRoot.Controls.Add(this.flpVoiceRow, 0, 5);
            this.tlpRoot.Controls.Add(this.lblHotkeyHint, 0, 6);
            this.tlpRoot.Controls.Add(this.txtLog, 0, 7);
            this.tlpRoot.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpRoot.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRoot.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpRoot.ColumnCount = 1;
            this.tlpRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpRoot.RowCount = 8;
            this.tlpRoot.Padding = new System.Windows.Forms.Padding(12);
            this.tlpRoot.Name = "tlpRoot";
            // 
            // flpAdminBanner
            // 
            this.flpAdminBanner.Controls.Add(this.lblAdminWarning);
            this.flpAdminBanner.Controls.Add(this.btnRestartAdmin);
            this.flpAdminBanner.AutoSize = true;
            this.flpAdminBanner.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(244)))), ((int)(((byte)(206)))));
            this.flpAdminBanner.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpAdminBanner.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(48)))), ((int)(((byte)(0)))));
            this.flpAdminBanner.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpAdminBanner.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.flpAdminBanner.Padding = new System.Windows.Forms.Padding(6);
            this.flpAdminBanner.Name = "flpAdminBanner";
            // 
            // lblAdminWarning
            // 
            this.lblAdminWarning.AutoSize = true;
            this.lblAdminWarning.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(48)))), ((int)(((byte)(0)))));
            this.lblAdminWarning.Text = "Not running as Administrator — disabling/enabling hubs needs admin rights.";
            this.lblAdminWarning.Margin = new System.Windows.Forms.Padding(0, 8, 8, 0);
            this.lblAdminWarning.Name = "lblAdminWarning";
            // 
            // btnRestartAdmin
            // 
            this.btnRestartAdmin.AutoSize = true;
            this.btnRestartAdmin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(82)))), ((int)(((byte)(0)))));
            this.btnRestartAdmin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRestartAdmin.Font = new System.Drawing.Font("Segoe UI Semibold", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnRestartAdmin.ForeColor = System.Drawing.Color.White;
            this.btnRestartAdmin.Padding = new System.Windows.Forms.Padding(6, 2, 6, 2);
            this.btnRestartAdmin.Text = "Restart as Administrator";
            this.btnRestartAdmin.UseVisualStyleBackColor = false;
            this.btnRestartAdmin.Name = "btnRestartAdmin";
            this.btnRestartAdmin.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(58)))), ((int)(((byte)(0)))));
            this.btnRestartAdmin.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(175)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            // 
            // lblDevice
            // 
            this.lblDevice.AutoSize = true;
            this.lblDevice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblDevice.Text = "USB hub / controller to arm:";
            this.lblDevice.Margin = new System.Windows.Forms.Padding(0, 8, 0, 2);
            this.lblDevice.Name = "lblDevice";
            // 
            // flpDeviceRow
            // 
            this.flpDeviceRow.Controls.Add(this.cboDevices);
            this.flpDeviceRow.Controls.Add(this.btnRefresh);
            this.flpDeviceRow.AutoSize = true;
            this.flpDeviceRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpDeviceRow.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpDeviceRow.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpDeviceRow.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpDeviceRow.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.flpDeviceRow.Name = "flpDeviceRow";
            // 
            // cboDevices
            // 
            this.cboDevices.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.cboDevices.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDevices.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboDevices.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.cboDevices.FormattingEnabled = true;
            this.cboDevices.Size = new System.Drawing.Size(520, 25);
            this.cboDevices.Name = "cboDevices";
            // 
            // btnRefresh
            // 
            this.btnRefresh.AutoSize = true;
            this.btnRefresh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnRefresh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRefresh.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnRefresh.Margin = new System.Windows.Forms.Padding(3);
            this.btnRefresh.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.UseVisualStyleBackColor = false;
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnRefresh.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // flpCountdownRow
            // 
            this.flpCountdownRow.Controls.Add(this.lblCountdown);
            this.flpCountdownRow.Controls.Add(this.nudSeconds);
            this.flpCountdownRow.Controls.Add(this.lblTimeLeftCaption);
            this.flpCountdownRow.Controls.Add(this.lblTimeLeft);
            this.flpCountdownRow.AutoSize = true;
            this.flpCountdownRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpCountdownRow.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpCountdownRow.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpCountdownRow.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpCountdownRow.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.flpCountdownRow.Name = "flpCountdownRow";
            // 
            // lblCountdown
            // 
            this.lblCountdown.AutoSize = true;
            this.lblCountdown.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblCountdown.Text = "Countdown (seconds, fallback if you don't hit the hotkey):";
            this.lblCountdown.Margin = new System.Windows.Forms.Padding(0, 6, 4, 0);
            this.lblCountdown.Name = "lblCountdown";
            // 
            // nudSeconds
            // 
            this.nudSeconds.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.nudSeconds.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.nudSeconds.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.nudSeconds.Size = new System.Drawing.Size(60, 24);
            this.nudSeconds.Maximum = new decimal(new int[] {
            120,
            0,
            0,
            0});
            this.nudSeconds.Minimum = new decimal(new int[] {
            3,
            0,
            0,
            0});
            this.nudSeconds.Value = new decimal(new int[] {
            10,
            0,
            0,
            0});
            this.nudSeconds.Name = "nudSeconds";
            // 
            // lblTimeLeftCaption
            // 
            this.lblTimeLeftCaption.AutoSize = true;
            this.lblTimeLeftCaption.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblTimeLeftCaption.Text = "Time left:";
            this.lblTimeLeftCaption.Margin = new System.Windows.Forms.Padding(24, 6, 0, 0);
            this.lblTimeLeftCaption.Name = "lblTimeLeftCaption";
            // 
            // lblTimeLeft
            // 
            this.lblTimeLeft.AutoSize = true;
            this.lblTimeLeft.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblTimeLeft.Text = "--";
            this.lblTimeLeft.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.lblTimeLeft.Margin = new System.Windows.Forms.Padding(8, 0, 0, 0);
            this.lblTimeLeft.MinimumSize = new System.Drawing.Size(90, 0);
            this.lblTimeLeft.Name = "lblTimeLeft";
            // 
            // flpActionRow
            // 
            this.flpActionRow.Controls.Add(this.btnToggle);
            this.flpActionRow.Controls.Add(this.btnReenableAll);
            this.flpActionRow.AutoSize = true;
            this.flpActionRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpActionRow.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpActionRow.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpActionRow.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpActionRow.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.flpActionRow.Name = "flpActionRow";
            // 
            // btnToggle
            // 
            this.btnToggle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(150)))), ((int)(((byte)(85)))));
            this.btnToggle.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnToggle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnToggle.ForeColor = System.Drawing.Color.White;
            this.btnToggle.Size = new System.Drawing.Size(380, 52);
            this.btnToggle.Text = "Enabled — click to Disable && Arm";
            this.btnToggle.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnToggle.UseVisualStyleBackColor = false;
            this.btnToggle.Name = "btnToggle";
            // 
            // btnReenableAll
            // 
            this.btnReenableAll.AutoSize = false;
            this.btnReenableAll.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnReenableAll.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReenableAll.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnReenableAll.Margin = new System.Windows.Forms.Padding(3);
            this.btnReenableAll.Padding = new System.Windows.Forms.Padding(0);
            this.btnReenableAll.Text = "Re-enable All";
            this.btnReenableAll.UseVisualStyleBackColor = false;
            this.btnReenableAll.Size = new System.Drawing.Size(180, 52);
            this.btnReenableAll.Name = "btnReenableAll";
            this.btnReenableAll.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnReenableAll.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            // 
            // flpVoiceRow
            // 
            this.flpVoiceRow.Controls.Add(this.chkVoice);
            this.flpVoiceRow.Controls.Add(this.lblSayAny);
            this.flpVoiceRow.Controls.Add(this.txtPhrases);
            this.flpVoiceRow.Controls.Add(this.lblMinConfidence);
            this.flpVoiceRow.Controls.Add(this.nudConfidence);
            this.flpVoiceRow.AutoSize = true;
            this.flpVoiceRow.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpVoiceRow.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpVoiceRow.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpVoiceRow.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flpVoiceRow.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.flpVoiceRow.Name = "flpVoiceRow";
            // 
            // chkVoice
            // 
            this.chkVoice.AutoSize = true;
            this.chkVoice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.chkVoice.Text = "Voice trigger";
            this.chkVoice.UseVisualStyleBackColor = false;
            this.chkVoice.Margin = new System.Windows.Forms.Padding(0, 6, 12, 0);
            this.chkVoice.Name = "chkVoice";
            // 
            // lblSayAny
            // 
            this.lblSayAny.AutoSize = true;
            this.lblSayAny.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblSayAny.Text = "Say any of:";
            this.lblSayAny.Margin = new System.Windows.Forms.Padding(0, 6, 4, 0);
            this.lblSayAny.Name = "lblSayAny";
            // 
            // txtPhrases
            // 
            this.txtPhrases.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.txtPhrases.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPhrases.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtPhrases.Size = new System.Drawing.Size(220, 24);
            this.txtPhrases.Text = "go, trigger, enable now";
            this.txtPhrases.Name = "txtPhrases";
            // 
            // lblMinConfidence
            // 
            this.lblMinConfidence.AutoSize = true;
            this.lblMinConfidence.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblMinConfidence.Text = "Min confidence %:";
            this.lblMinConfidence.Margin = new System.Windows.Forms.Padding(12, 6, 4, 0);
            this.lblMinConfidence.Name = "lblMinConfidence";
            // 
            // nudConfidence
            // 
            this.nudConfidence.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.nudConfidence.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.nudConfidence.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.nudConfidence.Size = new System.Drawing.Size(55, 24);
            this.nudConfidence.Maximum = new decimal(new int[] {
            99,
            0,
            0,
            0});
            this.nudConfidence.Minimum = new decimal(new int[] {
            40,
            0,
            0,
            0});
            this.nudConfidence.Value = new decimal(new int[] {
            70,
            0,
            0,
            0});
            this.nudConfidence.Name = "nudConfidence";
            // 
            // lblHotkeyHint
            // 
            this.lblHotkeyHint.AutoSize = true;
            this.lblHotkeyHint.ForeColor = System.Drawing.Color.DimGray;
            this.lblHotkeyHint.Text = "Global hotkeys (work from any module, even unfocused): Ctrl+Alt+D disable/arm, Ctrl+Alt+E enable now.\r\nIf your keyboard or a USB microphone shares the hub you disable, that trigger dies with it — the countdown is your fallback.";
            this.lblHotkeyHint.Margin = new System.Windows.Forms.Padding(0, 6, 0, 6);
            this.lblHotkeyHint.Name = "lblHotkeyHint";
            // 
            // txtLog
            // 
            this.txtLog.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.txtLog.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtLog.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.txtLog.ReadOnly = true;
            this.txtLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtLog.Font = new System.Drawing.Font("Consolas", 10F);
            this.txtLog.Multiline = true;
            this.txtLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtLog.Name = "txtLog";
            // 
            // UsbTriggerView
            // 
            this.Controls.Add(this.tlpRoot);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.Size = new System.Drawing.Size(1000, 680);
            this.Name = "UsbTriggerView";
            ((System.ComponentModel.ISupportInitialize)(this.nudConfidence)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudSeconds)).EndInit();
            this.flpVoiceRow.ResumeLayout(false);
            this.flpVoiceRow.PerformLayout();
            this.flpActionRow.ResumeLayout(false);
            this.flpActionRow.PerformLayout();
            this.flpCountdownRow.ResumeLayout(false);
            this.flpCountdownRow.PerformLayout();
            this.flpDeviceRow.ResumeLayout(false);
            this.flpDeviceRow.PerformLayout();
            this.flpAdminBanner.ResumeLayout(false);
            this.flpAdminBanner.PerformLayout();
            this.tlpRoot.ResumeLayout(false);
            this.tlpRoot.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.TableLayoutPanel tlpRoot;
        internal System.Windows.Forms.FlowLayoutPanel flpAdminBanner;
        internal System.Windows.Forms.Label lblAdminWarning;
        internal System.Windows.Forms.Button btnRestartAdmin;
        internal System.Windows.Forms.Label lblDevice;
        internal System.Windows.Forms.FlowLayoutPanel flpDeviceRow;
        internal System.Windows.Forms.ComboBox cboDevices;
        internal System.Windows.Forms.Button btnRefresh;
        internal System.Windows.Forms.FlowLayoutPanel flpCountdownRow;
        internal System.Windows.Forms.Label lblCountdown;
        internal System.Windows.Forms.NumericUpDown nudSeconds;
        internal System.Windows.Forms.Label lblTimeLeftCaption;
        internal System.Windows.Forms.Label lblTimeLeft;
        internal System.Windows.Forms.FlowLayoutPanel flpActionRow;
        internal System.Windows.Forms.Button btnToggle;
        internal System.Windows.Forms.Button btnReenableAll;
        internal System.Windows.Forms.FlowLayoutPanel flpVoiceRow;
        internal System.Windows.Forms.CheckBox chkVoice;
        internal System.Windows.Forms.Label lblSayAny;
        internal System.Windows.Forms.TextBox txtPhrases;
        internal System.Windows.Forms.Label lblMinConfidence;
        internal System.Windows.Forms.NumericUpDown nudConfidence;
        internal System.Windows.Forms.Label lblHotkeyHint;
        internal System.Windows.Forms.TextBox txtLog;
    }
}
