// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger
{
    partial class HelpForm
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.txtBlurb = new System.Windows.Forms.TextBox();
            this.lnkReadme = new System.Windows.Forms.LinkLabel();
            this.lblFooter = new System.Windows.Forms.Label();
            this.btnOk = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // txtBlurb
            // 
            this.txtBlurb.BackColor = System.Drawing.SystemColors.Control;
            this.txtBlurb.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.txtBlurb.Location = new System.Drawing.Point(16, 16);
            this.txtBlurb.Multiline = true;
            this.txtBlurb.ReadOnly = true;
            this.txtBlurb.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtBlurb.Size = new System.Drawing.Size(428, 330);
            this.txtBlurb.Name = "txtBlurb";
            // 
            // lnkReadme
            // 
            this.lnkReadme.AutoSize = true;
            this.lnkReadme.Location = new System.Drawing.Point(16, 356);
            this.lnkReadme.Text = "View the full README on GitHub";
            this.lnkReadme.Name = "lnkReadme";
            this.lnkReadme.Click += new System.EventHandler(this.lnkReadme_Click);
            // 
            // lblFooter
            // 
            this.lblFooter.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblFooter.ForeColor = System.Drawing.SystemColors.GrayText;
            this.lblFooter.Location = new System.Drawing.Point(16, 388);
            this.lblFooter.Size = new System.Drawing.Size(300, 18);
            this.lblFooter.Text = "Developer: HaKDMoDz™";
            this.lblFooter.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblFooter.Name = "lblFooter";
            // 
            // btnOk
            // 
            this.btnOk.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOk.Location = new System.Drawing.Point(368, 404);
            this.btnOk.Size = new System.Drawing.Size(76, 28);
            this.btnOk.Text = "OK";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Name = "btnOk";
            // 
            // HelpForm
            // 
            this.Controls.Add(this.txtBlurb);
            this.Controls.Add(this.lnkReadme);
            this.Controls.Add(this.lblFooter);
            this.Controls.Add(this.btnOk);
            this.AcceptButton = this.btnOk;
            this.ClientSize = new System.Drawing.Size(460, 444);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Mobile Surgery — Help";
            this.Name = "HelpForm";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox txtBlurb;
        private System.Windows.Forms.LinkLabel lnkReadme;
        private System.Windows.Forms.Label lblFooter;
        private System.Windows.Forms.Button btnOk;
    }
}
