// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger
{
    partial class MainForm
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.canvas = new TestPointTrigger.CanvasPanel();
            this.pnlSide = new System.Windows.Forms.Panel();
            this.pnlListHost = new System.Windows.Forms.Panel();
            this.lvPads = new System.Windows.Forms.ListView();
            this.chPadNo = new System.Windows.Forms.ColumnHeader();
            this.chPadX = new System.Windows.Forms.ColumnHeader();
            this.chPadY = new System.Windows.Forms.ColumnHeader();
            this.chPadSource = new System.Windows.Forms.ColumnHeader();
            this.tlpSettings = new System.Windows.Forms.TableLayoutPanel();
            this.lblHdrDetection = new System.Windows.Forms.Label();
            this.lblMinRadius = new System.Windows.Forms.Label();
            this.tbMinRadius = new System.Windows.Forms.TrackBar();
            this.lblMaxRadius = new System.Windows.Forms.Label();
            this.tbMaxRadius = new System.Windows.Forms.TrackBar();
            this.lblRoundness = new System.Windows.Forms.Label();
            this.tbRoundness = new System.Windows.Forms.TrackBar();
            this.flpPadKinds = new System.Windows.Forms.FlowLayoutPanel();
            this.chkGold = new System.Windows.Forms.CheckBox();
            this.chkWhite = new System.Windows.Forms.CheckBox();
            this.lblHdrLabels = new System.Windows.Forms.Label();
            this.flpLabelSize = new System.Windows.Forms.FlowLayoutPanel();
            this.lblLabelSize = new System.Windows.Forms.Label();
            this.nudLabelSize = new System.Windows.Forms.NumericUpDown();
            this.flpUpscale = new System.Windows.Forms.FlowLayoutPanel();
            this.lblUpscale = new System.Windows.Forms.Label();
            this.nudUpscale = new System.Windows.Forms.NumericUpDown();
            this.flpLabelButtons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnLabelColour = new System.Windows.Forms.Button();
            this.btnResetDefaults = new System.Windows.Forms.Button();
            this.lblHdrPads = new System.Windows.Forms.Label();
            this.toolMain = new System.Windows.Forms.ToolStrip();
            this.tsbOpen = new System.Windows.Forms.ToolStripButton();
            this.tsbDetect = new System.Windows.Forms.ToolStripButton();
            this.tss1 = new System.Windows.Forms.ToolStripSeparator();
            this.tsbPan = new System.Windows.Forms.ToolStripButton();
            this.tsbEdit = new System.Windows.Forms.ToolStripButton();
            this.tsbCrop = new System.Windows.Forms.ToolStripButton();
            this.tsbBox = new System.Windows.Forms.ToolStripButton();
            this.tss2 = new System.Windows.Forms.ToolStripSeparator();
            this.tslStyle = new System.Windows.Forms.ToolStripLabel();
            this.tscStyle = new System.Windows.Forms.ToolStripComboBox();
            this.tss3 = new System.Windows.Forms.ToolStripSeparator();
            this.tsbFit = new System.Windows.Forms.ToolStripButton();
            this.tsbUndo = new System.Windows.Forms.ToolStripButton();
            this.tsbExportPng = new System.Windows.Forms.ToolStripButton();
            this.tsbExportCsv = new System.Windows.Forms.ToolStripButton();
            this.menuMain = new System.Windows.Forms.MenuStrip();
            this.mnuFile = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuOpen = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuPaste = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSep1 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuExportPng = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuExportCsv = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSep2 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuExit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuEdit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuUndo = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuClearManual = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuClearCrop = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuClearBox = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelp = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHowTo = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuAbout = new System.Windows.Forms.ToolStripMenuItem();
            this.statusMain = new System.Windows.Forms.StatusStrip();
            this.lblStatus = new System.Windows.Forms.ToolStripStatusLabel();
            this.lblCredit = new System.Windows.Forms.ToolStripStatusLabel();
            ((System.ComponentModel.ISupportInitialize)(this.tbMinRadius)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tbMaxRadius)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tbRoundness)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudLabelSize)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudUpscale)).BeginInit();
            this.pnlSide.SuspendLayout();
            this.pnlListHost.SuspendLayout();
            this.tlpSettings.SuspendLayout();
            this.flpPadKinds.SuspendLayout();
            this.flpLabelSize.SuspendLayout();
            this.flpUpscale.SuspendLayout();
            this.flpLabelButtons.SuspendLayout();
            this.toolMain.SuspendLayout();
            this.menuMain.SuspendLayout();
            this.statusMain.SuspendLayout();
            this.SuspendLayout();
            // 
            // canvas
            // 
            this.canvas.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(28)))));
            this.canvas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.canvas.Name = "canvas";
            this.canvas.Paint += new System.Windows.Forms.PaintEventHandler(this.PaintCanvas);
            this.canvas.MouseDown += new System.Windows.Forms.MouseEventHandler(this.CanvasDown);
            this.canvas.MouseMove += new System.Windows.Forms.MouseEventHandler(this.CanvasMove);
            this.canvas.MouseUp += new System.Windows.Forms.MouseEventHandler(this.CanvasUp);
            this.canvas.Resize += new System.EventHandler(this.canvas_Resize);
            // 
            // pnlSide
            // 
            this.pnlSide.Controls.Add(this.pnlListHost);
            this.pnlSide.Controls.Add(this.tlpSettings);
            this.pnlSide.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.pnlSide.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlSide.Dock = System.Windows.Forms.DockStyle.Right;
            this.pnlSide.Padding = new System.Windows.Forms.Padding(8);
            this.pnlSide.Size = new System.Drawing.Size(300, 780);
            this.pnlSide.Name = "pnlSide";
            // 
            // pnlListHost
            // 
            this.pnlListHost.Controls.Add(this.lvPads);
            this.pnlListHost.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.pnlListHost.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlListHost.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlListHost.Padding = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.pnlListHost.Name = "pnlListHost";
            // 
            // lvPads
            // 
            this.lvPads.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.chPadNo,
            this.chPadX,
            this.chPadY,
            this.chPadSource});
            this.lvPads.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lvPads.FullRowSelect = true;
            this.lvPads.HideSelection = false;
            this.lvPads.UseCompatibleStateImageBehavior = false;
            this.lvPads.View = System.Windows.Forms.View.Details;
            this.lvPads.Name = "lvPads";
            this.lvPads.SelectedIndexChanged += new System.EventHandler(this.lvPads_SelectedIndexChanged);
            // 
            // chPadNo
            // 
            this.chPadNo.Text = "#";
            this.chPadNo.Width = 40;
            this.chPadNo.Name = "chPadNo";
            // 
            // chPadX
            // 
            this.chPadX.Text = "X";
            this.chPadX.Width = 60;
            this.chPadX.Name = "chPadX";
            // 
            // chPadY
            // 
            this.chPadY.Text = "Y";
            this.chPadY.Width = 60;
            this.chPadY.Name = "chPadY";
            // 
            // chPadSource
            // 
            this.chPadSource.Text = "Source";
            this.chPadSource.Width = 90;
            this.chPadSource.Name = "chPadSource";
            // 
            // tlpSettings
            // 
            this.tlpSettings.Controls.Add(this.lblHdrDetection, 0, 0);
            this.tlpSettings.Controls.Add(this.lblMinRadius, 0, 1);
            this.tlpSettings.Controls.Add(this.tbMinRadius, 0, 2);
            this.tlpSettings.Controls.Add(this.lblMaxRadius, 0, 3);
            this.tlpSettings.Controls.Add(this.tbMaxRadius, 0, 4);
            this.tlpSettings.Controls.Add(this.lblRoundness, 0, 5);
            this.tlpSettings.Controls.Add(this.tbRoundness, 0, 6);
            this.tlpSettings.Controls.Add(this.flpPadKinds, 0, 7);
            this.tlpSettings.Controls.Add(this.lblHdrLabels, 0, 8);
            this.tlpSettings.Controls.Add(this.flpLabelSize, 0, 9);
            this.tlpSettings.Controls.Add(this.flpUpscale, 0, 10);
            this.tlpSettings.Controls.Add(this.flpLabelButtons, 0, 11);
            this.tlpSettings.Controls.Add(this.lblHdrPads, 0, 12);
            this.tlpSettings.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpSettings.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.tlpSettings.ColumnCount = 1;
            this.tlpSettings.Dock = System.Windows.Forms.DockStyle.Top;
            this.tlpSettings.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.tlpSettings.RowCount = 13;
            this.tlpSettings.AutoSize = true;
            this.tlpSettings.Name = "tlpSettings";
            // 
            // lblHdrDetection
            // 
            this.lblHdrDetection.AutoSize = true;
            this.lblHdrDetection.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblHdrDetection.Text = "Detection";
            this.lblHdrDetection.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblHdrDetection.Margin = new System.Windows.Forms.Padding(0, 10, 0, 2);
            this.lblHdrDetection.Name = "lblHdrDetection";
            // 
            // lblMinRadius
            // 
            this.lblMinRadius.AutoSize = true;
            this.lblMinRadius.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblMinRadius.Text = "Min pad radius (px)";
            this.lblMinRadius.Margin = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.lblMinRadius.Name = "lblMinRadius";
            // 
            // tbMinRadius
            // 
            this.tbMinRadius.AutoSize = false;
            this.tbMinRadius.Maximum = 40;
            this.tbMinRadius.Minimum = 2;
            this.tbMinRadius.Size = new System.Drawing.Size(270, 28);
            this.tbMinRadius.TickStyle = System.Windows.Forms.TickStyle.None;
            this.tbMinRadius.Value = 4;
            this.tbMinRadius.Name = "tbMinRadius";
            this.tbMinRadius.ValueChanged += new System.EventHandler(this.Slider_ValueChanged);
            // 
            // lblMaxRadius
            // 
            this.lblMaxRadius.AutoSize = true;
            this.lblMaxRadius.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblMaxRadius.Text = "Max pad radius (px)";
            this.lblMaxRadius.Margin = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.lblMaxRadius.Name = "lblMaxRadius";
            // 
            // tbMaxRadius
            // 
            this.tbMaxRadius.AutoSize = false;
            this.tbMaxRadius.Maximum = 200;
            this.tbMaxRadius.Minimum = 10;
            this.tbMaxRadius.Size = new System.Drawing.Size(270, 28);
            this.tbMaxRadius.TickStyle = System.Windows.Forms.TickStyle.None;
            this.tbMaxRadius.Value = 45;
            this.tbMaxRadius.Name = "tbMaxRadius";
            this.tbMaxRadius.ValueChanged += new System.EventHandler(this.Slider_ValueChanged);
            // 
            // lblRoundness
            // 
            this.lblRoundness.AutoSize = true;
            this.lblRoundness.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblRoundness.Text = "Core roundness";
            this.lblRoundness.Margin = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.lblRoundness.Name = "lblRoundness";
            // 
            // tbRoundness
            // 
            this.tbRoundness.AutoSize = false;
            this.tbRoundness.Maximum = 80;
            this.tbRoundness.Minimum = 15;
            this.tbRoundness.Size = new System.Drawing.Size(270, 28);
            this.tbRoundness.TickStyle = System.Windows.Forms.TickStyle.None;
            this.tbRoundness.Value = 35;
            this.tbRoundness.Name = "tbRoundness";
            this.tbRoundness.ValueChanged += new System.EventHandler(this.Slider_ValueChanged);
            // 
            // flpPadKinds
            // 
            this.flpPadKinds.Controls.Add(this.chkGold);
            this.flpPadKinds.Controls.Add(this.chkWhite);
            this.flpPadKinds.AutoSize = true;
            this.flpPadKinds.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpPadKinds.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpPadKinds.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpPadKinds.Name = "flpPadKinds";
            // 
            // chkGold
            // 
            this.chkGold.AutoSize = true;
            this.chkGold.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.chkGold.Text = "Gold pads";
            this.chkGold.UseVisualStyleBackColor = false;
            this.chkGold.Checked = true;
            this.chkGold.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkGold.Name = "chkGold";
            this.chkGold.CheckedChanged += new System.EventHandler(this.chkPadKind_CheckedChanged);
            // 
            // chkWhite
            // 
            this.chkWhite.AutoSize = true;
            this.chkWhite.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.chkWhite.Text = "White/tinned pads";
            this.chkWhite.UseVisualStyleBackColor = false;
            this.chkWhite.Checked = true;
            this.chkWhite.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkWhite.Name = "chkWhite";
            this.chkWhite.CheckedChanged += new System.EventHandler(this.chkPadKind_CheckedChanged);
            // 
            // lblHdrLabels
            // 
            this.lblHdrLabels.AutoSize = true;
            this.lblHdrLabels.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblHdrLabels.Text = "Labels & export";
            this.lblHdrLabels.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblHdrLabels.Margin = new System.Windows.Forms.Padding(0, 10, 0, 2);
            this.lblHdrLabels.Name = "lblHdrLabels";
            // 
            // flpLabelSize
            // 
            this.flpLabelSize.Controls.Add(this.lblLabelSize);
            this.flpLabelSize.Controls.Add(this.nudLabelSize);
            this.flpLabelSize.AutoSize = true;
            this.flpLabelSize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpLabelSize.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpLabelSize.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpLabelSize.WrapContents = false;
            this.flpLabelSize.Name = "flpLabelSize";
            // 
            // lblLabelSize
            // 
            this.lblLabelSize.AutoSize = true;
            this.lblLabelSize.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblLabelSize.Text = "Label size (px)";
            this.lblLabelSize.Margin = new System.Windows.Forms.Padding(0, 6, 8, 0);
            this.lblLabelSize.MinimumSize = new System.Drawing.Size(150, 0);
            this.lblLabelSize.Name = "lblLabelSize";
            // 
            // nudLabelSize
            // 
            this.nudLabelSize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.nudLabelSize.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.nudLabelSize.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.nudLabelSize.Size = new System.Drawing.Size(70, 24);
            this.nudLabelSize.DecimalPlaces = 1;
            this.nudLabelSize.Increment = new decimal(new int[] {
            5,
            0,
            0,
            65536});
            this.nudLabelSize.Maximum = new decimal(new int[] {
            60,
            0,
            0,
            0});
            this.nudLabelSize.Minimum = new decimal(new int[] {
            4,
            0,
            0,
            0});
            this.nudLabelSize.Value = new decimal(new int[] {
            11,
            0,
            0,
            0});
            this.nudLabelSize.Name = "nudLabelSize";
            this.nudLabelSize.ValueChanged += new System.EventHandler(this.nudLabelSize_ValueChanged);
            // 
            // flpUpscale
            // 
            this.flpUpscale.Controls.Add(this.lblUpscale);
            this.flpUpscale.Controls.Add(this.nudUpscale);
            this.flpUpscale.AutoSize = true;
            this.flpUpscale.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpUpscale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpUpscale.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpUpscale.WrapContents = false;
            this.flpUpscale.Name = "flpUpscale";
            // 
            // lblUpscale
            // 
            this.lblUpscale.AutoSize = true;
            this.lblUpscale.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblUpscale.Text = "Export upscale ×";
            this.lblUpscale.Margin = new System.Windows.Forms.Padding(0, 6, 8, 0);
            this.lblUpscale.MinimumSize = new System.Drawing.Size(150, 0);
            this.lblUpscale.Name = "lblUpscale";
            // 
            // nudUpscale
            // 
            this.nudUpscale.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.nudUpscale.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.nudUpscale.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.nudUpscale.Size = new System.Drawing.Size(70, 24);
            this.nudUpscale.DecimalPlaces = 1;
            this.nudUpscale.Increment = new decimal(new int[] {
            5,
            0,
            0,
            65536});
            this.nudUpscale.Maximum = new decimal(new int[] {
            6,
            0,
            0,
            0});
            this.nudUpscale.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudUpscale.Value = new decimal(new int[] {
            3,
            0,
            0,
            0});
            this.nudUpscale.Name = "nudUpscale";
            // 
            // flpLabelButtons
            // 
            this.flpLabelButtons.Controls.Add(this.btnLabelColour);
            this.flpLabelButtons.Controls.Add(this.btnResetDefaults);
            this.flpLabelButtons.AutoSize = true;
            this.flpLabelButtons.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.flpLabelButtons.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flpLabelButtons.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.flpLabelButtons.Name = "flpLabelButtons";
            // 
            // btnLabelColour
            // 
            this.btnLabelColour.AutoSize = true;
            this.btnLabelColour.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnLabelColour.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLabelColour.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnLabelColour.Margin = new System.Windows.Forms.Padding(3);
            this.btnLabelColour.Padding = new System.Windows.Forms.Padding(0);
            this.btnLabelColour.Text = "Label colour…";
            this.btnLabelColour.UseVisualStyleBackColor = false;
            this.btnLabelColour.Name = "btnLabelColour";
            this.btnLabelColour.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnLabelColour.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            this.btnLabelColour.Click += new System.EventHandler(this.btnLabelColour_Click);
            // 
            // btnResetDefaults
            // 
            this.btnResetDefaults.AutoSize = true;
            this.btnResetDefaults.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(18)))), ((int)(((byte)(32)))));
            this.btnResetDefaults.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnResetDefaults.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(220)))), ((int)(((byte)(242)))));
            this.btnResetDefaults.Margin = new System.Windows.Forms.Padding(3);
            this.btnResetDefaults.Padding = new System.Windows.Forms.Padding(0);
            this.btnResetDefaults.Text = "Reset defaults";
            this.btnResetDefaults.UseVisualStyleBackColor = false;
            this.btnResetDefaults.Name = "btnResetDefaults";
            this.btnResetDefaults.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.btnResetDefaults.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(26)))), ((int)(((byte)(40)))));
            this.btnResetDefaults.Click += new System.EventHandler(this.btnResetDefaults_Click);
            // 
            // lblHdrPads
            // 
            this.lblHdrPads.AutoSize = true;
            this.lblHdrPads.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblHdrPads.Text = "Pads (click to locate)";
            this.lblHdrPads.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblHdrPads.Margin = new System.Windows.Forms.Padding(0, 10, 0, 2);
            this.lblHdrPads.Name = "lblHdrPads";
            // 
            // toolMain
            // 
            this.toolMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsbOpen,
            this.tsbDetect,
            this.tss1,
            this.tsbPan,
            this.tsbEdit,
            this.tsbCrop,
            this.tsbBox,
            this.tss2,
            this.tslStyle,
            this.tscStyle,
            this.tss3,
            this.tsbFit,
            this.tsbUndo,
            this.tsbExportPng,
            this.tsbExportCsv});
            this.toolMain.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(24)))), ((int)(((byte)(34)))));
            this.toolMain.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden;
            this.toolMain.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.toolMain.Name = "toolMain";
            // 
            // tsbOpen
            // 
            this.tsbOpen.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbOpen.Text = "📂 Open";
            this.tsbOpen.Name = "tsbOpen";
            this.tsbOpen.Click += new System.EventHandler(this.mnuOpen_Click);
            // 
            // tsbDetect
            // 
            this.tsbDetect.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbDetect.Text = "🔍 Detect";
            this.tsbDetect.Name = "tsbDetect";
            this.tsbDetect.Click += new System.EventHandler(this.tsbDetect_Click);
            // 
            // tss1
            // 
            this.tss1.Name = "tss1";
            // 
            // tsbPan
            // 
            this.tsbPan.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbPan.Text = "✋ Pan";
            this.tsbPan.Name = "tsbPan";
            this.tsbPan.Click += new System.EventHandler(this.tsbPan_Click);
            // 
            // tsbEdit
            // 
            this.tsbEdit.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbEdit.Text = "✚ Edit pads";
            this.tsbEdit.Name = "tsbEdit";
            this.tsbEdit.Click += new System.EventHandler(this.tsbEdit_Click);
            // 
            // tsbCrop
            // 
            this.tsbCrop.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbCrop.Text = "⬚ Crop to board";
            this.tsbCrop.Name = "tsbCrop";
            this.tsbCrop.Click += new System.EventHandler(this.tsbCrop_Click);
            // 
            // tsbBox
            // 
            this.tsbBox.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbBox.Text = "▧ Box detect";
            this.tsbBox.Name = "tsbBox";
            this.tsbBox.Click += new System.EventHandler(this.tsbBox_Click);
            // 
            // tss2
            // 
            this.tss2.Name = "tss2";
            // 
            // tslStyle
            // 
            this.tslStyle.Text = "Style:";
            this.tslStyle.Name = "tslStyle";
            // 
            // tscStyle
            // 
            this.tscStyle.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.tscStyle.Items.AddRange(new object[] {
            "Labels only",
            "Circles + labels"});
            this.tscStyle.Size = new System.Drawing.Size(150, 28);
            this.tscStyle.Name = "tscStyle";
            this.tscStyle.SelectedIndexChanged += new System.EventHandler(this.tscStyle_SelectedIndexChanged);
            // 
            // tss3
            // 
            this.tss3.Name = "tss3";
            // 
            // tsbFit
            // 
            this.tsbFit.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbFit.Text = "⤢ Fit";
            this.tsbFit.Name = "tsbFit";
            this.tsbFit.Click += new System.EventHandler(this.tsbFit_Click);
            // 
            // tsbUndo
            // 
            this.tsbUndo.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbUndo.Text = "↶ Undo";
            this.tsbUndo.Name = "tsbUndo";
            this.tsbUndo.Click += new System.EventHandler(this.mnuUndo_Click);
            // 
            // tsbExportPng
            // 
            this.tsbExportPng.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbExportPng.Text = "💾 Export PNG";
            this.tsbExportPng.Name = "tsbExportPng";
            this.tsbExportPng.Click += new System.EventHandler(this.mnuExportPng_Click);
            // 
            // tsbExportCsv
            // 
            this.tsbExportCsv.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.tsbExportCsv.Text = "📄 Export CSV";
            this.tsbExportCsv.Name = "tsbExportCsv";
            this.tsbExportCsv.Click += new System.EventHandler(this.mnuExportCsv_Click);
            // 
            // menuMain
            // 
            this.menuMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFile,
            this.mnuEdit,
            this.mnuHelp});
            this.menuMain.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(24)))), ((int)(((byte)(34)))));
            this.menuMain.Name = "menuMain";
            // 
            // mnuFile
            // 
            this.mnuFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuOpen,
            this.mnuPaste,
            this.mnuSep1,
            this.mnuExportPng,
            this.mnuExportCsv,
            this.mnuSep2,
            this.mnuExit});
            this.mnuFile.Text = "&File";
            this.mnuFile.Name = "mnuFile";
            // 
            // mnuOpen
            // 
            this.mnuOpen.Text = "&Open image…";
            this.mnuOpen.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
            this.mnuOpen.Name = "mnuOpen";
            this.mnuOpen.Click += new System.EventHandler(this.mnuOpen_Click);
            // 
            // mnuPaste
            // 
            this.mnuPaste.Text = "&Paste image";
            this.mnuPaste.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
            this.mnuPaste.Name = "mnuPaste";
            this.mnuPaste.Click += new System.EventHandler(this.mnuPaste_Click);
            // 
            // mnuSep1
            // 
            this.mnuSep1.Name = "mnuSep1";
            // 
            // mnuExportPng
            // 
            this.mnuExportPng.Text = "Export labelled &PNG…";
            this.mnuExportPng.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
            this.mnuExportPng.Name = "mnuExportPng";
            this.mnuExportPng.Click += new System.EventHandler(this.mnuExportPng_Click);
            // 
            // mnuExportCsv
            // 
            this.mnuExportCsv.Text = "Export &CSV checklist…";
            this.mnuExportCsv.Name = "mnuExportCsv";
            this.mnuExportCsv.Click += new System.EventHandler(this.mnuExportCsv_Click);
            // 
            // mnuSep2
            // 
            this.mnuSep2.Name = "mnuSep2";
            // 
            // mnuExit
            // 
            this.mnuExit.Text = "E&xit";
            this.mnuExit.Name = "mnuExit";
            this.mnuExit.Click += new System.EventHandler(this.mnuExit_Click);
            // 
            // mnuEdit
            // 
            this.mnuEdit.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuUndo,
            this.mnuClearManual,
            this.mnuClearCrop,
            this.mnuClearBox});
            this.mnuEdit.Text = "&Edit";
            this.mnuEdit.Name = "mnuEdit";
            // 
            // mnuUndo
            // 
            this.mnuUndo.Text = "&Undo";
            this.mnuUndo.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
            this.mnuUndo.Name = "mnuUndo";
            this.mnuUndo.Click += new System.EventHandler(this.mnuUndo_Click);
            // 
            // mnuClearManual
            // 
            this.mnuClearManual.Text = "Clear &manual edits";
            this.mnuClearManual.Name = "mnuClearManual";
            this.mnuClearManual.Click += new System.EventHandler(this.mnuClearManual_Click);
            // 
            // mnuClearCrop
            // 
            this.mnuClearCrop.Text = "Clear c&rop";
            this.mnuClearCrop.Name = "mnuClearCrop";
            this.mnuClearCrop.Click += new System.EventHandler(this.mnuClearCrop_Click);
            // 
            // mnuClearBox
            // 
            this.mnuClearBox.Text = "Clear &box detections";
            this.mnuClearBox.Name = "mnuClearBox";
            this.mnuClearBox.Click += new System.EventHandler(this.mnuClearBox_Click);
            // 
            // mnuHelp
            // 
            this.mnuHelp.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuHowTo,
            this.mnuAbout});
            this.mnuHelp.Text = "&Help";
            this.mnuHelp.Name = "mnuHelp";
            // 
            // mnuHowTo
            // 
            this.mnuHowTo.Text = "&How to use";
            this.mnuHowTo.Name = "mnuHowTo";
            this.mnuHowTo.Click += new System.EventHandler(this.mnuHowTo_Click);
            // 
            // mnuAbout
            // 
            this.mnuAbout.Text = "&About";
            this.mnuAbout.Name = "mnuAbout";
            this.mnuAbout.Click += new System.EventHandler(this.mnuAbout_Click);
            // 
            // statusMain
            // 
            this.statusMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.lblStatus,
            this.lblCredit});
            this.statusMain.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(24)))), ((int)(((byte)(34)))));
            this.statusMain.Name = "statusMain";
            // 
            // lblStatus
            // 
            this.lblStatus.Spring = true;
            this.lblStatus.Text = "Ready";
            this.lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStatus.Name = "lblStatus";
            // 
            // lblCredit
            // 
            this.lblCredit.ForeColor = System.Drawing.Color.DimGray;
            this.lblCredit.Text = "Developer: HaKDMoDz™";
            this.lblCredit.Name = "lblCredit";
            // 
            // MainForm
            // 
            this.Controls.Add(this.canvas);
            this.Controls.Add(this.pnlSide);
            this.Controls.Add(this.toolMain);
            this.Controls.Add(this.menuMain);
            this.Controls.Add(this.statusMain);
            this.AllowDrop = true;
            this.ClientSize = new System.Drawing.Size(1384, 861);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.KeyPreview = true;
            this.MainMenuStrip = this.menuMain;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mobile Surgery — PCB Pad Finder";
            this.DragDrop += new System.Windows.Forms.DragEventHandler(this.MainForm_DragDrop);
            this.DragEnter += new System.Windows.Forms.DragEventHandler(this.MainForm_DragEnter);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.OnKey);
            this.Name = "MainForm";
            ((System.ComponentModel.ISupportInitialize)(this.nudUpscale)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudLabelSize)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tbRoundness)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tbMaxRadius)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tbMinRadius)).EndInit();
            this.statusMain.ResumeLayout(false);
            this.statusMain.PerformLayout();
            this.menuMain.ResumeLayout(false);
            this.menuMain.PerformLayout();
            this.toolMain.ResumeLayout(false);
            this.toolMain.PerformLayout();
            this.flpLabelButtons.ResumeLayout(false);
            this.flpLabelButtons.PerformLayout();
            this.flpUpscale.ResumeLayout(false);
            this.flpUpscale.PerformLayout();
            this.flpLabelSize.ResumeLayout(false);
            this.flpLabelSize.PerformLayout();
            this.flpPadKinds.ResumeLayout(false);
            this.flpPadKinds.PerformLayout();
            this.tlpSettings.ResumeLayout(false);
            this.tlpSettings.PerformLayout();
            this.pnlListHost.ResumeLayout(false);
            this.pnlListHost.PerformLayout();
            this.pnlSide.ResumeLayout(false);
            this.pnlSide.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal TestPointTrigger.CanvasPanel canvas;
        internal System.Windows.Forms.Panel pnlSide;
        internal System.Windows.Forms.Panel pnlListHost;
        internal System.Windows.Forms.ListView lvPads;
        internal System.Windows.Forms.ColumnHeader chPadNo;
        internal System.Windows.Forms.ColumnHeader chPadX;
        internal System.Windows.Forms.ColumnHeader chPadY;
        internal System.Windows.Forms.ColumnHeader chPadSource;
        internal System.Windows.Forms.TableLayoutPanel tlpSettings;
        internal System.Windows.Forms.Label lblHdrDetection;
        internal System.Windows.Forms.Label lblMinRadius;
        internal System.Windows.Forms.TrackBar tbMinRadius;
        internal System.Windows.Forms.Label lblMaxRadius;
        internal System.Windows.Forms.TrackBar tbMaxRadius;
        internal System.Windows.Forms.Label lblRoundness;
        internal System.Windows.Forms.TrackBar tbRoundness;
        internal System.Windows.Forms.FlowLayoutPanel flpPadKinds;
        internal System.Windows.Forms.CheckBox chkGold;
        internal System.Windows.Forms.CheckBox chkWhite;
        internal System.Windows.Forms.Label lblHdrLabels;
        internal System.Windows.Forms.FlowLayoutPanel flpLabelSize;
        internal System.Windows.Forms.Label lblLabelSize;
        internal System.Windows.Forms.NumericUpDown nudLabelSize;
        internal System.Windows.Forms.FlowLayoutPanel flpUpscale;
        internal System.Windows.Forms.Label lblUpscale;
        internal System.Windows.Forms.NumericUpDown nudUpscale;
        internal System.Windows.Forms.FlowLayoutPanel flpLabelButtons;
        internal System.Windows.Forms.Button btnLabelColour;
        internal System.Windows.Forms.Button btnResetDefaults;
        internal System.Windows.Forms.Label lblHdrPads;
        internal System.Windows.Forms.ToolStrip toolMain;
        internal System.Windows.Forms.ToolStripButton tsbOpen;
        internal System.Windows.Forms.ToolStripButton tsbDetect;
        internal System.Windows.Forms.ToolStripSeparator tss1;
        internal System.Windows.Forms.ToolStripButton tsbPan;
        internal System.Windows.Forms.ToolStripButton tsbEdit;
        internal System.Windows.Forms.ToolStripButton tsbCrop;
        internal System.Windows.Forms.ToolStripButton tsbBox;
        internal System.Windows.Forms.ToolStripSeparator tss2;
        internal System.Windows.Forms.ToolStripLabel tslStyle;
        internal System.Windows.Forms.ToolStripComboBox tscStyle;
        internal System.Windows.Forms.ToolStripSeparator tss3;
        internal System.Windows.Forms.ToolStripButton tsbFit;
        internal System.Windows.Forms.ToolStripButton tsbUndo;
        internal System.Windows.Forms.ToolStripButton tsbExportPng;
        internal System.Windows.Forms.ToolStripButton tsbExportCsv;
        internal System.Windows.Forms.MenuStrip menuMain;
        internal System.Windows.Forms.ToolStripMenuItem mnuFile;
        internal System.Windows.Forms.ToolStripMenuItem mnuOpen;
        internal System.Windows.Forms.ToolStripMenuItem mnuPaste;
        internal System.Windows.Forms.ToolStripSeparator mnuSep1;
        internal System.Windows.Forms.ToolStripMenuItem mnuExportPng;
        internal System.Windows.Forms.ToolStripMenuItem mnuExportCsv;
        internal System.Windows.Forms.ToolStripSeparator mnuSep2;
        internal System.Windows.Forms.ToolStripMenuItem mnuExit;
        internal System.Windows.Forms.ToolStripMenuItem mnuEdit;
        internal System.Windows.Forms.ToolStripMenuItem mnuUndo;
        internal System.Windows.Forms.ToolStripMenuItem mnuClearManual;
        internal System.Windows.Forms.ToolStripMenuItem mnuClearCrop;
        internal System.Windows.Forms.ToolStripMenuItem mnuClearBox;
        internal System.Windows.Forms.ToolStripMenuItem mnuHelp;
        internal System.Windows.Forms.ToolStripMenuItem mnuHowTo;
        internal System.Windows.Forms.ToolStripMenuItem mnuAbout;
        internal System.Windows.Forms.StatusStrip statusMain;
        internal System.Windows.Forms.ToolStripStatusLabel lblStatus;
        internal System.Windows.Forms.ToolStripStatusLabel lblCredit;
    }
}
