// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules
{
    partial class LicenseEditForm
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tlpFields = new System.Windows.Forms.TableLayoutPanel();
            this.lblTool = new System.Windows.Forms.Label();
            this.txtTool = new System.Windows.Forms.TextBox();
            this.lblVendor = new System.Windows.Forms.Label();
            this.txtVendor = new System.Windows.Forms.TextBox();
            this.lblCategory = new System.Windows.Forms.Label();
            this.cboCategory = new System.Windows.Forms.ComboBox();
            this.lblType = new System.Windows.Forms.Label();
            this.cboType = new System.Windows.Forms.ComboBox();
            this.lblKey = new System.Windows.Forms.Label();
            this.txtKey = new System.Windows.Forms.TextBox();
            this.lblAccount = new System.Windows.Forms.Label();
            this.txtAccount = new System.Windows.Forms.TextBox();
            this.lblHardwareId = new System.Windows.Forms.Label();
            this.txtHardwareId = new System.Windows.Forms.TextBox();
            this.lblPurchased = new System.Windows.Forms.Label();
            this.dtpPurchased = new System.Windows.Forms.DateTimePicker();
            this.lblExpires = new System.Windows.Forms.Label();
            this.dtpExpires = new System.Windows.Forms.DateTimePicker();
            this.lblCredits = new System.Windows.Forms.Label();
            this.nudCredits = new System.Windows.Forms.NumericUpDown();
            this.lblCost = new System.Windows.Forms.Label();
            this.txtCost = new System.Windows.Forms.TextBox();
            this.lblStatus = new System.Windows.Forms.Label();
            this.cboStatus = new System.Windows.Forms.ComboBox();
            this.lblUrl = new System.Windows.Forms.Label();
            this.txtUrl = new System.Windows.Forms.TextBox();
            this.lblNotes = new System.Windows.Forms.Label();
            this.txtNotes = new System.Windows.Forms.TextBox();
            this.flpButtons = new System.Windows.Forms.FlowLayoutPanel();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.nudCredits)).BeginInit();
            this.tlpFields.SuspendLayout();
            this.flpButtons.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpFields
            // 
            this.tlpFields.Controls.Add(this.lblTool, 0, 0);
            this.tlpFields.Controls.Add(this.txtTool, 1, 0);
            this.tlpFields.Controls.Add(this.lblVendor, 0, 1);
            this.tlpFields.Controls.Add(this.txtVendor, 1, 1);
            this.tlpFields.Controls.Add(this.lblCategory, 0, 2);
            this.tlpFields.Controls.Add(this.cboCategory, 1, 2);
            this.tlpFields.Controls.Add(this.lblType, 0, 3);
            this.tlpFields.Controls.Add(this.cboType, 1, 3);
            this.tlpFields.Controls.Add(this.lblKey, 0, 4);
            this.tlpFields.Controls.Add(this.txtKey, 1, 4);
            this.tlpFields.Controls.Add(this.lblAccount, 0, 5);
            this.tlpFields.Controls.Add(this.txtAccount, 1, 5);
            this.tlpFields.Controls.Add(this.lblHardwareId, 0, 6);
            this.tlpFields.Controls.Add(this.txtHardwareId, 1, 6);
            this.tlpFields.Controls.Add(this.lblPurchased, 0, 7);
            this.tlpFields.Controls.Add(this.dtpPurchased, 1, 7);
            this.tlpFields.Controls.Add(this.lblExpires, 0, 8);
            this.tlpFields.Controls.Add(this.dtpExpires, 1, 8);
            this.tlpFields.Controls.Add(this.lblCredits, 0, 9);
            this.tlpFields.Controls.Add(this.nudCredits, 1, 9);
            this.tlpFields.Controls.Add(this.lblCost, 0, 10);
            this.tlpFields.Controls.Add(this.txtCost, 1, 10);
            this.tlpFields.Controls.Add(this.lblStatus, 0, 11);
            this.tlpFields.Controls.Add(this.cboStatus, 1, 11);
            this.tlpFields.Controls.Add(this.lblUrl, 0, 12);
            this.tlpFields.Controls.Add(this.txtUrl, 1, 12);
            this.tlpFields.Controls.Add(this.lblNotes, 0, 13);
            this.tlpFields.Controls.Add(this.txtNotes, 1, 13);
            this.tlpFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.tlpFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.AutoScroll = true;
            this.tlpFields.ColumnCount = 2;
            this.tlpFields.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpFields.Padding = new System.Windows.Forms.Padding(12);
            this.tlpFields.RowCount = 14;
            this.tlpFields.Name = "tlpFields";
            // 
            // lblTool
            // 
            this.lblTool.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblTool.AutoSize = true;
            this.lblTool.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblTool.Text = "Tool *";
            this.lblTool.Name = "lblTool";
            // 
            // txtTool
            // 
            this.txtTool.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtTool.Size = new System.Drawing.Size(320, 23);
            this.txtTool.Name = "txtTool";
            // 
            // lblVendor
            // 
            this.lblVendor.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblVendor.AutoSize = true;
            this.lblVendor.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblVendor.Text = "Vendor";
            this.lblVendor.Name = "lblVendor";
            // 
            // txtVendor
            // 
            this.txtVendor.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtVendor.Size = new System.Drawing.Size(320, 23);
            this.txtVendor.Name = "txtVendor";
            // 
            // lblCategory
            // 
            this.lblCategory.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblCategory.AutoSize = true;
            this.lblCategory.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblCategory.Text = "Category";
            this.lblCategory.Name = "lblCategory";
            // 
            // cboCategory
            // 
            this.cboCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategory.FormattingEnabled = true;
            this.cboCategory.Items.AddRange(new object[] {
            "Forensic",
            "Servicing",
            "FRP",
            "Flashing",
            "Other"});
            this.cboCategory.Size = new System.Drawing.Size(200, 23);
            this.cboCategory.Name = "cboCategory";
            // 
            // lblType
            // 
            this.lblType.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblType.AutoSize = true;
            this.lblType.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblType.Text = "Licence type";
            this.lblType.Name = "lblType";
            // 
            // cboType
            // 
            this.cboType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboType.FormattingEnabled = true;
            this.cboType.Items.AddRange(new object[] {
            "Dongle",
            "Activation",
            "Credits",
            "Subscription",
            "Perpetual"});
            this.cboType.Size = new System.Drawing.Size(200, 23);
            this.cboType.Name = "cboType";
            // 
            // lblKey
            // 
            this.lblKey.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblKey.AutoSize = true;
            this.lblKey.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblKey.Text = "Licence key";
            this.lblKey.Name = "lblKey";
            // 
            // txtKey
            // 
            this.txtKey.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtKey.Size = new System.Drawing.Size(320, 23);
            this.txtKey.Name = "txtKey";
            // 
            // lblAccount
            // 
            this.lblAccount.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblAccount.AutoSize = true;
            this.lblAccount.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblAccount.Text = "Account";
            this.lblAccount.Name = "lblAccount";
            // 
            // txtAccount
            // 
            this.txtAccount.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtAccount.Size = new System.Drawing.Size(320, 23);
            this.txtAccount.Name = "txtAccount";
            // 
            // lblHardwareId
            // 
            this.lblHardwareId.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblHardwareId.AutoSize = true;
            this.lblHardwareId.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblHardwareId.Text = "Hardware/dongle ID";
            this.lblHardwareId.Name = "lblHardwareId";
            // 
            // txtHardwareId
            // 
            this.txtHardwareId.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtHardwareId.Size = new System.Drawing.Size(320, 23);
            this.txtHardwareId.Name = "txtHardwareId";
            // 
            // lblPurchased
            // 
            this.lblPurchased.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblPurchased.AutoSize = true;
            this.lblPurchased.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblPurchased.Text = "Purchased";
            this.lblPurchased.Name = "lblPurchased";
            // 
            // dtpPurchased
            // 
            this.dtpPurchased.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpPurchased.Size = new System.Drawing.Size(150, 23);
            this.dtpPurchased.ShowCheckBox = true;
            this.dtpPurchased.Name = "dtpPurchased";
            // 
            // lblExpires
            // 
            this.lblExpires.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblExpires.AutoSize = true;
            this.lblExpires.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblExpires.Text = "Expires";
            this.lblExpires.Name = "lblExpires";
            // 
            // dtpExpires
            // 
            this.dtpExpires.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpExpires.Size = new System.Drawing.Size(150, 23);
            this.dtpExpires.ShowCheckBox = true;
            this.dtpExpires.Name = "dtpExpires";
            // 
            // lblCredits
            // 
            this.lblCredits.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblCredits.AutoSize = true;
            this.lblCredits.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblCredits.Text = "Credits left";
            this.lblCredits.Name = "lblCredits";
            // 
            // nudCredits
            // 
            this.nudCredits.Maximum = new decimal(new int[] {
            1000000000,
            0,
            0,
            0});
            this.nudCredits.Size = new System.Drawing.Size(100, 23);
            this.nudCredits.Name = "nudCredits";
            // 
            // lblCost
            // 
            this.lblCost.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblCost.AutoSize = true;
            this.lblCost.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblCost.Text = "Cost";
            this.lblCost.Name = "lblCost";
            // 
            // txtCost
            // 
            this.txtCost.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtCost.Size = new System.Drawing.Size(120, 23);
            this.txtCost.Name = "txtCost";
            // 
            // lblStatus
            // 
            this.lblStatus.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblStatus.AutoSize = true;
            this.lblStatus.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblStatus.Text = "Status";
            this.lblStatus.Name = "lblStatus";
            // 
            // cboStatus
            // 
            this.cboStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboStatus.FormattingEnabled = true;
            this.cboStatus.Items.AddRange(new object[] {
            "Active",
            "Expired",
            "Suspended"});
            this.cboStatus.Size = new System.Drawing.Size(200, 23);
            this.cboStatus.Name = "cboStatus";
            // 
            // lblUrl
            // 
            this.lblUrl.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblUrl.AutoSize = true;
            this.lblUrl.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblUrl.Text = "Vendor URL";
            this.lblUrl.Name = "lblUrl";
            // 
            // txtUrl
            // 
            this.txtUrl.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtUrl.Size = new System.Drawing.Size(320, 23);
            this.txtUrl.Name = "txtUrl";
            // 
            // lblNotes
            // 
            this.lblNotes.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.lblNotes.AutoSize = true;
            this.lblNotes.Margin = new System.Windows.Forms.Padding(0, 6, 6, 6);
            this.lblNotes.Text = "Notes";
            this.lblNotes.Name = "lblNotes";
            // 
            // txtNotes
            // 
            this.txtNotes.Multiline = true;
            this.txtNotes.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtNotes.Size = new System.Drawing.Size(380, 80);
            this.txtNotes.Name = "txtNotes";
            // 
            // flpButtons
            // 
            this.flpButtons.Controls.Add(this.btnCancel);
            this.flpButtons.Controls.Add(this.btnSave);
            this.flpButtons.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.flpButtons.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.flpButtons.Padding = new System.Windows.Forms.Padding(10);
            this.flpButtons.Size = new System.Drawing.Size(540, 46);
            this.flpButtons.Name = "flpButtons";
            // 
            // btnCancel
            // 
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Size = new System.Drawing.Size(90, 27);
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Name = "btnCancel";
            // 
            // btnSave
            // 
            this.btnSave.Size = new System.Drawing.Size(90, 27);
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = true;
            this.btnSave.Name = "btnSave";
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // LicenseEditForm
            // 
            this.Controls.Add(this.tlpFields);
            this.Controls.Add(this.flpButtons);
            this.AcceptButton = this.btnSave;
            this.CancelButton = this.btnCancel;
            this.ClientSize = new System.Drawing.Size(540, 640);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Edit tool / licence";
            this.Name = "LicenseEditForm";
            ((System.ComponentModel.ISupportInitialize)(this.nudCredits)).EndInit();
            this.flpButtons.ResumeLayout(false);
            this.flpButtons.PerformLayout();
            this.tlpFields.ResumeLayout(false);
            this.tlpFields.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpFields;
        private System.Windows.Forms.Label lblTool;
        private System.Windows.Forms.TextBox txtTool;
        private System.Windows.Forms.Label lblVendor;
        private System.Windows.Forms.TextBox txtVendor;
        private System.Windows.Forms.Label lblCategory;
        private System.Windows.Forms.ComboBox cboCategory;
        private System.Windows.Forms.Label lblType;
        private System.Windows.Forms.ComboBox cboType;
        private System.Windows.Forms.Label lblKey;
        private System.Windows.Forms.TextBox txtKey;
        private System.Windows.Forms.Label lblAccount;
        private System.Windows.Forms.TextBox txtAccount;
        private System.Windows.Forms.Label lblHardwareId;
        private System.Windows.Forms.TextBox txtHardwareId;
        private System.Windows.Forms.Label lblPurchased;
        private System.Windows.Forms.DateTimePicker dtpPurchased;
        private System.Windows.Forms.Label lblExpires;
        private System.Windows.Forms.DateTimePicker dtpExpires;
        private System.Windows.Forms.Label lblCredits;
        private System.Windows.Forms.NumericUpDown nudCredits;
        private System.Windows.Forms.Label lblCost;
        private System.Windows.Forms.TextBox txtCost;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.ComboBox cboStatus;
        private System.Windows.Forms.Label lblUrl;
        private System.Windows.Forms.TextBox txtUrl;
        private System.Windows.Forms.Label lblNotes;
        private System.Windows.Forms.TextBox txtNotes;
        private System.Windows.Forms.FlowLayoutPanel flpButtons;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
    }
}
