// <auto-generated>
//   Visual Studio WinForms designer file. Edit visually in Design View.
// </auto-generated>
namespace TestPointTrigger.Modules
{
    partial class ModuleHostForm
    {
        /// <summary>Required designer variable.</summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>Clean up any resources being used.</summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlViewHost = new System.Windows.Forms.Panel();
            this.heroCard = new TestPointTrigger.HeroCard();
            this.pnlFooter = new System.Windows.Forms.Panel();
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblVersion = new System.Windows.Forms.Label();
            this.pnlSidebar = new System.Windows.Forms.Panel();
            this.lstNav = new System.Windows.Forms.ListBox();
            this.lblSideFoot = new System.Windows.Forms.Label();
            this.cardLogo = new TestPointTrigger.Card();
            this.lblLogoTitle = new System.Windows.Forms.Label();
            this.lblLogoSubtitle = new System.Windows.Forms.Label();
            this.pnlMain.SuspendLayout();
            this.pnlFooter.SuspendLayout();
            this.pnlSidebar.SuspendLayout();
            this.cardLogo.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnlMain
            // 
            this.pnlMain.Controls.Add(this.pnlViewHost);
            this.pnlMain.Controls.Add(this.heroCard);
            this.pnlMain.Controls.Add(this.pnlFooter);
            this.pnlMain.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.pnlMain.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Padding = new System.Windows.Forms.Padding(24, 18, 24, 0);
            this.pnlMain.Name = "pnlMain";
            // 
            // pnlViewHost
            // 
            this.pnlViewHost.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.pnlViewHost.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlViewHost.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlViewHost.Name = "pnlViewHost";
            // 
            // heroCard
            // 
            this.heroCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.heroCard.Dock = System.Windows.Forms.DockStyle.Top;
            this.heroCard.Padding = new System.Windows.Forms.Padding(0, 0, 0, 12);
            this.heroCard.Size = new System.Drawing.Size(1068, 120);
            this.heroCard.Name = "heroCard";
            // 
            // pnlFooter
            // 
            this.pnlFooter.Controls.Add(this.lblStatus);
            this.pnlFooter.Controls.Add(this.lblVersion);
            this.pnlFooter.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.pnlFooter.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlFooter.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlFooter.Size = new System.Drawing.Size(1068, 34);
            this.pnlFooter.Name = "pnlFooter";
            // 
            // lblStatus
            // 
            this.lblStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatus.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblStatus.Text = "Ready";
            this.lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStatus.Name = "lblStatus";
            // 
            // lblVersion
            // 
            this.lblVersion.Dock = System.Windows.Forms.DockStyle.Right;
            this.lblVersion.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblVersion.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(107)))), ((int)(((byte)(122)))));
            this.lblVersion.Size = new System.Drawing.Size(260, 34);
            this.lblVersion.Text = "Developer: HaKDMoDz™";
            this.lblVersion.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVersion.Name = "lblVersion";
            // 
            // pnlSidebar
            // 
            this.pnlSidebar.Controls.Add(this.lstNav);
            this.pnlSidebar.Controls.Add(this.lblSideFoot);
            this.pnlSidebar.Controls.Add(this.cardLogo);
            this.pnlSidebar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(13)))), ((int)(((byte)(20)))));
            this.pnlSidebar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.pnlSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlSidebar.Padding = new System.Windows.Forms.Padding(16);
            this.pnlSidebar.Size = new System.Drawing.Size(288, 881);
            this.pnlSidebar.Name = "pnlSidebar";
            // 
            // lstNav
            // 
            this.lstNav.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(13)))), ((int)(((byte)(20)))));
            this.lstNav.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstNav.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstNav.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.lstNav.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.lstNav.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lstNav.FormattingEnabled = true;
            this.lstNav.IntegralHeight = false;
            this.lstNav.ItemHeight = 46;
            this.lstNav.Name = "lstNav";
            this.lstNav.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.DrawNavItem);
            this.lstNav.SelectedIndexChanged += new System.EventHandler(this.lstNav_SelectedIndexChanged);
            this.lstNav.MouseLeave += new System.EventHandler(this.lstNav_MouseLeave);
            this.lstNav.MouseMove += new System.Windows.Forms.MouseEventHandler(this.lstNav_MouseMove);
            // 
            // lblSideFoot
            // 
            this.lblSideFoot.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblSideFoot.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblSideFoot.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(107)))), ((int)(((byte)(122)))));
            this.lblSideFoot.Padding = new System.Windows.Forms.Padding(4, 8, 4, 0);
            this.lblSideFoot.Size = new System.Drawing.Size(256, 96);
            this.lblSideFoot.Text = "Modular bench toolkit\r\nCamera coaching · USB trigger · ADB/Fastboot ·\r\npad finder · job database — one shell.";
            this.lblSideFoot.Name = "lblSideFoot";
            // 
            // cardLogo
            // 
            this.cardLogo.Controls.Add(this.lblLogoTitle);
            this.cardLogo.Controls.Add(this.lblLogoSubtitle);
            this.cardLogo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.cardLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.cardLogo.Fill = System.Drawing.Color.FromArgb(((int)(((byte)(13)))), ((int)(((byte)(21)))), ((int)(((byte)(33)))));
            this.cardLogo.Radius = 16;
            this.cardLogo.Size = new System.Drawing.Size(256, 82);
            this.cardLogo.Stroke = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(58)))), ((int)(((byte)(75)))));
            this.cardLogo.Name = "cardLogo";
            this.cardLogo.Paint += new System.Windows.Forms.PaintEventHandler(this.cardLogo_Paint);
            // 
            // lblLogoTitle
            // 
            this.lblLogoTitle.AutoSize = true;
            this.lblLogoTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.lblLogoTitle.Text = "MOBILE SURGERY";
            this.lblLogoTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblLogoTitle.Font = new System.Drawing.Font("Segoe UI", 12.5F, System.Drawing.FontStyle.Bold);
            this.lblLogoTitle.Location = new System.Drawing.Point(82, 16);
            this.lblLogoTitle.Name = "lblLogoTitle";
            // 
            // lblLogoSubtitle
            // 
            this.lblLogoSubtitle.AutoSize = true;
            this.lblLogoSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(134)))), ((int)(((byte)(149)))), ((int)(((byte)(166)))));
            this.lblLogoSubtitle.Text = "Bench Suite";
            this.lblLogoSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.lblLogoSubtitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblLogoSubtitle.Location = new System.Drawing.Point(84, 42);
            this.lblLogoSubtitle.Name = "lblLogoSubtitle";
            // 
            // ModuleHostForm
            // 
            this.Controls.Add(this.pnlMain);
            this.Controls.Add(this.pnlSidebar);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(11)))), ((int)(((byte)(17)))));
            this.ClientSize = new System.Drawing.Size(1404, 881);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mobile Surgery — Bench Suite";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ModuleHostForm_FormClosing);
            this.Name = "ModuleHostForm";
            this.cardLogo.ResumeLayout(false);
            this.cardLogo.PerformLayout();
            this.pnlSidebar.ResumeLayout(false);
            this.pnlSidebar.PerformLayout();
            this.pnlFooter.ResumeLayout(false);
            this.pnlFooter.PerformLayout();
            this.pnlMain.ResumeLayout(false);
            this.pnlMain.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal System.Windows.Forms.Panel pnlMain;
        internal System.Windows.Forms.Panel pnlViewHost;
        internal TestPointTrigger.HeroCard heroCard;
        internal System.Windows.Forms.Panel pnlFooter;
        internal System.Windows.Forms.Label lblStatus;
        internal System.Windows.Forms.Label lblVersion;
        internal System.Windows.Forms.Panel pnlSidebar;
        internal System.Windows.Forms.ListBox lstNav;
        internal System.Windows.Forms.Label lblSideFoot;
        internal TestPointTrigger.Card cardLogo;
        internal System.Windows.Forms.Label lblLogoTitle;
        internal System.Windows.Forms.Label lblLogoSubtitle;
    }
}
