# Designer-file generator for TestPoint Trigger views.
# Emits VS-WinForms-designer-compatible .Designer.cs files from compact specs.
import os
from decimal import Decimal

ISI = {"DataGridView", "NumericUpDown", "PictureBox", "TrackBar", "SplitContainer"}

def full(t): return t if "." in t else "System.Windows.Forms." + t
def short(t): return t.split(".")[-1]

def s(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'

def col(r, g, b): return "System.Drawing.Color.FromArgb(((int)(((byte)(%d)))), ((int)(((byte)(%d)))), ((int)(((byte)(%d)))))" % (r, g, b)
def named(n): return "System.Drawing.Color." + n
def sysc(n): return "System.Drawing.SystemColors." + n
def pad(*a): return "new System.Windows.Forms.Padding(%s)" % ", ".join(str(x) for x in a)
def size(w, h): return "new System.Drawing.Size(%d, %d)" % (w, h)
def pt(x, y): return "new System.Drawing.Point(%d, %d)" % (x, y)
def font(name, sz, style=None):
    if not style: return 'new System.Drawing.Font("%s", %gF)' % (name, sz)
    parts = ["System.Drawing.FontStyle." + x for x in style.split("|")]
    st = parts[0] if len(parts) == 1 else "((System.Drawing.FontStyle)((" + " | ".join(parts) + ")))"
    return 'new System.Drawing.Font("%s", %gF, %s)' % (name, sz, st)
def enum(e): return "System.Windows.Forms." + e
def dec(v):
    d = Decimal(str(v)); sign, digits, exp = d.as_tuple()
    scale = -exp if exp < 0 else 0
    mant = int("".join(map(str, digits))) * (10 ** exp if exp > 0 else 1)
    flags = (scale << 16) | (0x80000000 if sign else 0)
    if flags >= 0x80000000: flags -= 0x100000000
    return "new decimal(new int[] {\n            %d,\n            0,\n            0,\n            %d})" % (mant, flags)
def keys(*k):
    if len(k) == 1: return "System.Windows.Forms.Keys." + k[0]
    return "((System.Windows.Forms.Keys)((" + " | ".join("System.Windows.Forms.Keys." + x for x in k) + ")))"
TRUE, FALSE = "true", "false"

class Ctl:
    def __init__(self, name, type_, props=None, kids=None, cell=None, slot=None,
                 columns=None, items=None, ddi=None, extra=None, styles=None):
        self.name, self.type = name, type_
        self.props = list(props.items()) if isinstance(props, dict) else list(props or [])
        self.kids = kids or []
        self.cell, self.slot = cell, slot
        self.columns = columns or []
        self.items = items or []
        self.ddi = ddi or []
        self.extra = extra or []
        self.styles = styles or {}
    def walk(self):
        yield self
        for group in (self.columns, self.items, self.ddi, self.kids):
            for c in group: yield from c.walk()

def style_expr(kind, st):
    t, v = st
    if t == "AutoSize": return "new System.Windows.Forms.%sStyle()" % kind if False else \
        "new System.Windows.Forms.%sStyle(System.Windows.Forms.SizeType.AutoSize)" % kind
    return "new System.Windows.Forms.%sStyle(System.Windows.Forms.SizeType.%s, %gF)" % (kind, t, v)

HEADER = "// <auto-generated>\n//   Visual Studio WinForms designer file. Edit visually in Design View.\n// </auto-generated>"

def emit(cls, ns, base, root_props, root_kids, path, locals_=None, root_extra=None, modifier="internal"):
    root = Ctl("this", base, root_props, root_kids, extra=root_extra)
    allc = [c for c in root.walk() if c is not root]
    names = [c.name for c in allc]
    dup = {n for n in names if names.count(n) > 1}
    if dup: raise SystemExit("duplicate names in %s: %s" % (cls, dup))
    needs_components = any(short(c.type) in ("ToolTip", "Timer") for c in allc)
    I = "            "
    L = [HEADER, "namespace " + ns, "{", "    partial class " + cls, "    {",
         "        /// <summary>Required designer variable.</summary>",
         "        private System.ComponentModel.IContainer components = null;", "",
         "        /// <summary>Clean up any resources being used.</summary>",
         "        /// <param name=\"disposing\">true if managed resources should be disposed; otherwise, false.</param>",
         "        protected override void Dispose(bool disposing)", "        {",
         "            if (disposing && (components != null))", "            {",
         "                components.Dispose();", "            }",
         "            base.Dispose(disposing);", "        }", "",
         "        #region Windows Form Designer generated code", "",
         "        /// <summary>", "        /// Required method for Designer support - do not modify",
         "        /// the contents of this method with the code editor.", "        /// </summary>",
         "        private void InitializeComponent()", "        {"]
    w = L.append
    if needs_components: w(I + "this.components = new System.ComponentModel.Container();")
    for ln in (locals_ or []): w(I + ln)
    for c in allc:
        if short(c.type) in ("ToolTip", "Timer"):
            w(I + "this.%s = new %s(this.components);" % (c.name, full(c.type)))
        else:
            w(I + "this.%s = new %s();" % (c.name, full(c.type)))
    for c in allc:
        if short(c.type) in ISI:
            w(I + "((System.ComponentModel.ISupportInitialize)(this.%s)).BeginInit();" % c.name)
    susp = []
    for c in allc:
        if short(c.type) == "SplitContainer":
            susp += [c.name + ".Panel1", c.name + ".Panel2", c.name]
        elif c.kids or c.items:
            susp.append(c.name)
    for n in susp: w(I + "this.%s.SuspendLayout();" % n)
    w(I + "this.SuspendLayout();")

    def block(c, target):
        out = []
        for k in c.kids:
            if short(c.type) == "SplitContainer":
                out.append("%s.%s.Controls.Add(this.%s);" % (target, k.slot or "Panel1", k.name))
            elif k.cell is not None:
                out.append("%s.Controls.Add(this.%s, %d, %d);" % (target, k.name, k.cell[0], k.cell[1]))
            else:
                out.append("%s.Controls.Add(this.%s);" % (target, k.name))
        if c.columns:
            ct = "System.Windows.Forms.ColumnHeader" if short(c.type) == "ListView" else "System.Windows.Forms.DataGridViewColumn"
            out.append("%s.Columns.AddRange(new %s[] {\n%s});" % (target, ct, ",\n".join(I + "this." + x.name for x in c.columns)))
        if c.items:
            out.append("%s.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {\n%s});" % (target, ",\n".join(I + "this." + x.name for x in c.items)))
        if c.ddi:
            out.append("%s.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {\n%s});" % (target, ",\n".join(I + "this." + x.name for x in c.ddi)))
        for kind, key in (("Column", "cols"), ("Row", "rows")):
            for st in c.styles.get(key, []):
                out.append("%s.%sStyles.Add(%s);" % (target, kind, style_expr(kind, st)))
        for k, v in c.props:
            if k == "Items":
                out.append("%s.Items.AddRange(new object[] {\n%s});" % (target, ",\n".join(I + s(x) for x in v)))
            else:
                out.append("%s.%s = %s;" % (target, k, v))
        if target != "this":
            out.append("%s.Name = %s;" % (target, s(c.name)))
        for x in c.extra: out.append(x.replace("{n}", target))
        return out

    for c in allc:
        w(I + "// "); w(I + "// " + c.name); w(I + "// ")
        for ln in block(c, "this." + c.name): w(I + ln)
    w(I + "// "); w(I + "// " + cls); w(I + "// ")
    for ln in block(root, "this"): w(I + ln)
    w(I + "this.Name = %s;" % s(cls))
    for c in reversed(allc):
        if short(c.type) in ISI:
            w(I + "((System.ComponentModel.ISupportInitialize)(this.%s)).EndInit();" % c.name)
    for n in reversed(susp):
        w(I + "this.%s.ResumeLayout(false);" % n)
        if not (n.endswith(".Panel1") or n.endswith(".Panel2")):
            w(I + "this.%s.PerformLayout();" % n)
    w(I + "this.ResumeLayout(false);")
    w(I + "this.PerformLayout();")
    w(""); w("        }"); w(""); w("        #endregion"); w("")
    for c in allc: w("        %s %s %s;" % (modifier, full(c.type), c.name))
    w("    }"); w("}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write("\n".join(L) + "\n")
    print("wrote %-40s %3d controls" % (os.path.basename(path), len(allc)))
